### ISSUE TITLE
Cannot change my password

### ISSUE THREAD

**Issue by hectorcorrea** [pod4lib/aggregator#156]
The User edit form gives errors on save:

```
2 errors prohibited this user from being saved:

    Password confirmation doesn't match Password
    Current password is invalid
```

Even though I entered my real password and the confirmation values matched (I tried multiple times and even using the auto-generated passwords on my browser.)

![Screen Shot 2020-11-11 at 2 28 06 PM](https://user-images.githubusercontent.com/568286/98855717-724ff080-242a-11eb-8bec-fd8a62c762c4.png)

**Comment by corylown** [comment]
I cannot duplicate the problem, but there a is a design/UX problem.

The first field labeled "Password" is actually for your NEW password if you want to change it.
The second field labeled "Password confirmation" is for confirmation of your NEW password if you want to change it.
The third field is for your current password.

We should improve the layout/labeling of these fields to be more clear.

**Comment by hectorcorrea** [comment]
I think that was it, I was misinterpreting the meaning of those labels. I just tested again and was able to change my password.
