### ISSUE TITLE
Fix up background job status reporting

### ISSUE THREAD

**Issue by mejackreed** [pod4lib/aggregator#254]
- [ ] prune completed jobs
- [ ] hide? do something about? duplicate status lines for the same job (caused by varying job UUIDs?)
- [ ] sort the list consistently

**Comment by mejackreed** [comment]
Thinking about approaches here...

Pruning - is it sufficient to say if a `JobTracker.status.to_h == {}` then we should prune it? Maybe a time condition also? This could create a race condition perhaps? Or do we just want to handle things that haven't been touched in x time?

Alternative to pruning.. we could cleanup using a sidekiq custom error handler to lookup `JobTracker` by job_id and then update the status or remove.

Sorting - is created_at sufficient?

Do the pruning strategies help cleanup the duplication?

**Comment by corylown** [comment]
This appears to duplication #317

**Comment by corylown** [comment]
Fixed via #317
