### ISSUE TITLE
Error when attempting to sign up

### ISSUE THREAD

**Issue by JustinUhr** [pod4lib/aggregator#266]
When trying to sign up, after entering email and password in both fields and clicking 'Sign Up', I got the following error:
![POD_signup_error](https://user-images.githubusercontent.com/56878072/101081915-b2614980-3578-11eb-9dbe-8ef70e36596d.png)

I was able to create an account successfully after being invited.
(sorry for the dark theme in the screenshot)

**Comment by thatbudakguy** [comment]
i think given discussion on #475 this can be closed, since open signups should (soon) be impossible — it will be done by admin invite instead. that will also remove the need for the captcha.

**Comment by corylown** [comment]
Individual sign-ups are going away so I'm closing this issue.
