### ISSUE TITLE
Job trackers do not get dismissed/appear stuck

### ISSUE THREAD

**Issue by anarchivist** [pod4lib/aggregator#318]
As reported by Dartmouth, the job trackers we provide in the organization dashboard often get "stuck" and don't update. This is particularly confusing as it's not clear whether an upload has successfully processed.

![Screen Shot 2021-02-23 at 2 21 18 PM](https://user-images.githubusercontent.com/73732/108916651-6ce67280-75e3-11eb-96ed-3c3a1cc84e48.png)

The task for this issue is to see why the job trackers aren't cleaned up properly, or whether some other failure, etc. is causing them to hang. A separate issue has been filed about the overall design needs for the job tracker (#317).

**Comment by corylown** [comment]
Fixed via #317
