### ISSUE TITLE
Add hashes for delta deletes and expose in resource lists

### ISSUE THREAD

**Issue by anarchivist** [pod4lib/aggregator#335]
Related to #334. The resource lists for delta deletes don't provide hashes, which forces `resync-sync` (and potentially other clients) to refetch them since it can't determine whether there were any changes. Would it be possible to find a way to hash these to avoid expensive downloads/time to recreate the delta lists?

**Comment by corylown** [comment]
Decided in meeting on 3/30/22 with @anarchivist & @JohnMarkOckerbloom that we're going to remove the inter-stream delete deltas from the resource lists. Closing this issue.
