### ISSUE TITLE
Ensure data harvesting functionality meets the requirements for ReShare

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#416]
clarify whether incremental or record-level access

**Comment by JohnMarkOckerbloom** [comment]
From our last discussion, it sounds like ReShare needs incremental access, but doesn't require record-level access.  (We could still provide it as part of general OAI-PMH functionality via the GetRecord method, but we don't expect Index Data to depend on it or to invoke it regularly.)  More details on my  "Additional notes based on Friday's workcycle meeting with Index Data people" comment on issue #417.

**Comment by corylown** [comment]
Closing this since it has been replaced by more specific issues related to implementing OAI-PMH
