### ISSUE TITLE
Investigate and document what production server and application monitoring is in place; is it what we want.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#423]

**Comment by JohnMarkOckerbloom** [comment]
Are there current standards or expectations for how monitoring is provided for other Stanford applications and servers with similar expected levels of support?  (There may well be; I'd be interested in seeing what they are if so.)

**Comment by JohnMarkOckerbloom** [comment]
One type of monitoring that could be particularly important for this application, possibly more so than other Stanford applications, is a monitoring of how much storage space is being used, and how fast storage usage is growing, with alarms raised if what's allocated is likely to run out soon.  Given the large amounts of data that providers may upload to the aggregator without advance notice, and the desirability of not having those uploads or their processing failing partway through, we may need to pay special attention to avoiding storage needs exceeding capacity.
