### ISSUE TITLE
Improve user registration and management

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#424]

**Comment by ggeisler** [comment]
I've posted several tickets related to user management (#436, #444, #446, #447) but those are primarily visual design improvements, although they also should clarify the user experience around user features a bit.

I wonder if this ticket was motivated by other user registration and management concerns, and if so, what are they?

One possibility might relate to recent user roles and permissions discussions (#451); if we come up with a more refined roles and permissions model, that might require we revise how users are managed in the app (e.g., something more sophisticated than our current Site users page that admins use to add or revoke admin permissions). Is there anything else?

**Comment by corylown** [comment]
@ggeisler this was intended to capture in a very general way that user registration and management need refinement. I'm going to close this because the issues you've created (and #451) capture this in more detail (thank you!).
