### ISSUE TITLE
Update Stanford DevOpsDocs to reflect production obligations and concerns

### ISSUE THREAD

**Issue by anarchivist** [pod4lib/aggregator#432]
In the late 2020 work cycle, we created some [placeholder DevOpsDocs](https://github.com/sul-dlss/DevOpsDocs/tree/master/projects/pod/) for the Aggregator. Given that the Aggregator will be integral to BorrowDirect and ReShare, it is critical to document any ops-related information here. We've also been asked to update this documentation by the Stanford Ops team.

See also #433.

**Comment by corylown** [comment]
Maybe address during same session as application monitory.

**Comment by corylown** [comment]
Closed via https://github.com/sul-dlss/DevOpsDocs/commit/d29031fbe42e2c909a01370df0494ed19584b8b2
