### ISSUE TITLE
Document data consumer access to data file sequencing and processing status.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#442]
Question from @JohnMarkOckerbloom:

> If data consumers have access to the files (either raw or normalized), do they also have access (programmatic as well as via the web interface) to data on when they were created (so they can also determine correct sequence for processing) and on whether processing them succeeded or failed?

**Comment by JohnMarkOckerbloom** [comment]
The document "Streams and their files" at https://github.com/pod4lib/aggregator/wiki/Streams-and-their-files/ says that "times of upload are available in the stream listings", but it might be useful to say something more here about how automated downloaders can get those times of upload, and also on whether and how automated clients can tell the status and/or outcome of processing of the files)

**Comment by corylown** [comment]
@JohnMarkOckerbloom here's an example response from resourcesync showing that each full dump and subsequent deltas are returned in order and are timestamped to make the order clear to data consumers:

```
% curl -H "Authorization: Bearer $ACCESS_TOKEN" --url http://localhost:3000/organizations/stanford/streams/f5450351-5199-4b96-988a-5f22cd0b90f7/normalized_resourcelist/marcxml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:rs="http://www.openarchives.org/rs/terms/">
  <rs:ln rel="up" href="http://localhost:3000/organizations/normalized_resourcelist/marcxml"/>
  <rs:md capability="resourcelist" at="2022-03-17T13:21:29Z"/>
  <url>
    <loc>http://localhost:3000/organizations/stanford/streams/f5450351-5199-4b96-988a-5f22cd0b90f7/removed_since_previous_stream</loc>
  </url>
  <url>
    <rs:md hash="md5:a40b358c846dfd8d7c1d170ea693e366" type="application/gzip" length="1136"/>
    <loc>http://localhost:3000/file/465/stanford-2022-03-16-full-marcxml.xml.gz</loc>
    <lastmod>2022-03-16T18:09:06Z</lastmod>
  </url>
  <url>
    <rs:md hash="md5:6cef38fccdcb2df865e7f3f60a0c7ce7" type="application/gzip" length="768"/>
    <loc>http://localhost:3000/file/469/marcxml.xml.gz</loc>
    <lastmod>2022-03-17T13:21:29Z</lastmod>
  </url>
  <url>
    <rs:md hash="md5:301280d1d51569b7c4dd2ae9912c929a" type="text/plain" length="8"/>
    <loc>http://localhost:3000/file/467/deletes.del.txt</loc>
    <lastmod>2022-03-17T13:21:29Z</lastmod>
  </url>
</urlset>
```

I will update the wiki docs with these details.

**Comment by corylown** [comment]
I've added this language to the "Streams and their files" wiki docs:

> Full dumps and deltas are displayed in the aggregator user interface with their timestamp in order from oldest to newest. Likewise, ResourceSync's response to a request for a resource list of normalized data lists the available full dumps and deltas in order from oldest to newest and contains a lastmod field containing a timestamp that can be used to determine processing order.

**Comment by JohnMarkOckerbloom** [comment]
Great, thanks!
