### ISSUE TITLE
Redefine Bootstrap's `primary` color

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#443]
In some upcoming issues I'll be posting mockups that use a different color for Bootstrap's `primary` class color than their default #0b5ed7, which is what we currently use in POD. I'm suggesting this update because the POD blue used prominently in the site topbar doesn't work well with Bootstrap's lighter primary blue color:

<img width="433" alt="Screen Shot 2022-03-03 at 5 16 27 PM" src="https://user-images.githubusercontent.com/101482/156674973-24945d7e-85a2-4e32-acda-8deb49caad25.png">

I'm not opinionated on exactly _how_ we do it, but I suggest we update our Sass variables such that when we use any Bootstrap `*-primary` class (e.g., `btn-primary`) it uses the same color as defined for the topbar background (currently `#0A2949`) so that they'll always match (even if we change the topbar background color):

<img width="564" alt="Screen Shot 2022-03-03 at 5 21 03 PM" src="https://user-images.githubusercontent.com/101482/156675346-8f56db4d-8004-430f-bc64-cf541ca47c96.png">

**Comment by thatbudakguy** [comment]
closed in favor of #459, via discussion with @ggeisler
