### ISSUE TITLE
Update layout and content of Devise-based pages

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#444]
In issue #436 I suggested a simple fix to the Devise-based sign-up/login pages. That issue only addresses the current layout problem with those pages, though, and as I work through the app more I've noticed other issues with the sign-up/login pages that ideally would also be addressed to create a more attractive and clear user experience. If we don't have time to revamp these pages as suggested below, #436 is the minimum we should do, but it would be better to do the more thorough revamp suggested below.

## Basic layout changes
As I noted in #436, I think we should introduce Bootstrap columns into these pages for better layout. In the mockups below, I've used a wrapper div with `class="col-md-8 offset-md-2` to position the form in the middle of the page, at the `md` breakpoint and larger, and keeping the width of the forms plenty wide but not full-page width. At below `md` I think it will be fine to give the form full-page width.

Other consistent layout choices:
- Center the page title
- Add a horizontal rule/bottom border to separate the main form from the potentially relevant but secondary ("Sign up", "Log in") and tertiary ("Forgot your password?") link actions
- Left-align the secondary actions for a given page with the left-edge of the form
- Right-align the tertiary actions with the right-edge of the form

Note that some page titles, field labels, and button labels are the same as the Devise default but others are updated a bit for better clarity.

Here's how the various pages would more or less look after those changes are made:

## Set password
This is the form you get if you are emailed an invite to sign up with POD.

<img width="992" alt="set-password" src="https://user-images.githubusercontent.com/101482/156677987-8fb2bf27-19bc-40dc-ba64-240e3730ce64.png">

---

## Sign up

<img width="992" alt="sign-up" src="https://user-images.githubusercontent.com/101482/156678167-c6de113d-4e65-45ee-99ec-21f85af42ced.png">

---

## Log in

<img width="992" alt="log-in" src="https://user-images.githubusercontent.com/101482/156678171-a76f5cb2-ea11-4e80-bf40-7a128b6c7140.png">

---

## Forgot password

<img width="992" alt="forgot-password" src="https://user-images.githubusercontent.com/101482/156678177-7519f2ba-3106-496c-b9f8-f69038eb503e.png">

---

## Resend confirmation instructions

<img width="992" alt="resend" src="https://user-images.githubusercontent.com/101482/156678195-318e865e-3846-4fdc-b160-2ddea77abc46.png">

---

**Comment by marlo-longley** [comment]
@ggeisler I'm working on this ticket and have a question about the lower secondary and tertiary links. I noticed you'd like some to be aligned left, and others right. In the markup unfortunately they aren't distinguished in that way; they simply link to their routes. For example, here's how the sign in vs. forgot password links are marked up:

```
  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <li><%= link_to t(".sign_up"), new_registration_path(resource_name), data: { turbolinks: false } %></li>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <li><%= link_to t(".forgot_your_password"), new_password_path(resource_name) %></li>
  <% end -%>
```

How do you feel about having everything aligned left? Or maybe you can give me more clarity on what counts as secondary vs. tertiary links.  Here's how it's looking now:
![Screen Shot 2022-03-15 at 15 53 07](https://user-images.githubusercontent.com/1328900/158486398-b9e8d7b9-3a5f-4c7f-9a3e-5374515e2fc8.png)

**Comment by ggeisler** [comment]
@marlo-longley When I was using the terms "secondary" and "tertiary" I wasn't referring to any formal definition (e.g., Bootstrap class). I was just distinguishing between the more likely-to-be-used links ("Sign up", "Log in") from the probably-rarely-used links ("Forgot your password", "Didn't receive confirmation instructions"). So the pattern I was suggesting is to always align "Sign up" and "Log in" to the left, and the other links to the right.

However, it's currently up in the air whether we want to surface the "Sign up" link (versus all new account creation done via explicit invitations), which means on most pages there would be nothing to align left. So, sure, for now at least I think it's fine to just align whatever links are on the page to the left. We can revisit the alignment if and when we think it's worth considering later on.
