### ISSUE TITLE
Decide on application name

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#445]
I'll mark this as a question, because there might be a valid reason for it for the time being, but in the long run I believe we should use consistent terminology for the name of POD in at least the main application. I don't think it's helpful to at least new users to POD to see both "POD Aggregator" and "POD Data Lake" displayed prominently in the application:

<img width="992" alt="Screen Shot 2022-03-04 at 9 46 52 AM" src="https://user-images.githubusercontent.com/101482/156805138-59643f41-e7f4-48ce-ae23-3cd4075fdd22.png">

Perhaps "POD Data Lake" was just a handy term for the focus of the last MVP workcycle? And "POD Aggregator" is the intended application name, long-term?

I'll be creating another issue related to updating the home page to be more useful to users, so making a decision about this would be helpful in working on that design.

**Comment by JohnMarkOckerbloom** [comment]
Let's bring this up at Friday's workcycle management meeting, since I expect we'll have at least one board person (Tom or Joe) there.  I'm personally fine with "POD Aggregator" for the application name, but if others really like having "Data Lake" in the name, or want something more distinctive or memorable, I'm open to considering other suggestions.

**Comment by thatbudakguy** [comment]
I also prefer "POD Aggregator" for the application name — it helps make clear that the app is wholly separate from its data. No data is stored in this repository, and if this application ceased to exist, the data (in its "lake") would still exist.

**Comment by corylown** [comment]
Decided at 3/11/2022 POD/ReShare workcycle management meeting to use the name "POD Aggregator" for the application name.
