### ISSUE TITLE
Update layout of user profile page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#447]
Related to #436 and #444.

As noted in #436, the Devise-based user pages include the `w-25` Bootstrap class, which makes the main content area of these pages unnecessarily narrow in most viewport widths:

<img width="250" alt="Screen Shot 2022-03-04 at 1 48 25 PM" src="https://user-images.githubusercontent.com/101482/156843575-bbbcc15f-8ba6-4aae-b3fc-30e27d367e1a.png">

Removing the `w-25` class should help the user profile page as well, however, if we can tackle the suggested approach in #444, I'd suggest we could also make some other minor improvements to the user profile page, as outlined below.

Below is a mockup of the suggested improvement, followed by notes on specifics:

<img width="991" alt="Screen Shot 2022-03-04 at 1 49 47 PM" src="https://user-images.githubusercontent.com/101482/156843382-b04c8427-de60-4579-bcc6-e44187b1b217.png">

---

- **A:** The suggested layout assumes the work in #444 has been completed, so the centered form and page title would likely be inherited from that work. (This layout doesn't match pages elsewhere in POD, but I think the user-related pages are distinct enough that it's fine, maybe even desirable, for them to have a separate layout.)

- **B:** Page title is renamed `User profile`. This should also be changed to an `h1` from the current `h2`, since the application is using page titles as `h1`s elsewhere. (I hope to do a more thorough a11y analysis of things during the workcycle.)
- **C:** This is likely the trickiest part of this issue: separating the basic user profile fields from the change password fields. I think it's important, though, because the current form is potentially confusing (e.g., do you need to enter your password in the first password field if you are just changing your job title?). Also, I believe currently **you are** required to provide your current password to change the basic profile fields, which might be a native Devise thing but seems unnecessary for how the POD application will be used. This page is not accessible unless the user is logged into POD, which seems sufficient proof of identity to me for the user to change their name or job title (I wonder if the email address input should be a read-only field, though. Perhaps we'd want to prevent a user who was invited to join an organization using a specific email address from later changing that email address without the person who invited them to their organization knowing?). So my suggestion is those three fields make up a separate form that the "Update" button (`btn-primary`) submits. 
	- The label of the first field is changed to "Email address". The input might be disabled, if people agree with my concern above.
	- "Cancel" returns the user to the previous page, same as the "Back" action does on the current profile page.
- **D:** This section splits out the password fields as a new form for the user to change their password. 
	- Section heading "Change password" is an `H2`
	- Fields are re-ordered so the user starts by entering their current password.
	- Hint is removed from current password field since the distinct section makes it pretty clear you need to enter all fields to change your password.
	- Field labels are changed for "New password" and "Confirm new password"
	- Submit button label is "Change password" and is a `btn-secondary`
- **E:** Change the section heading to "Cancel your account" and make it an `h2`. Style the "Cancel account" button with `btn-danger` so it is more clearly a destructive action.

## Additional (future?) layout updates
This might be too much for the current workcycle but in the future, the sections on this page might benefit from being separated  into three tabs:

- Edit profile
- Change password 
- Cancel account

For example, below I've kept the same section content as above (except for adding an intro paragraph to the Cancel account tab), but split the sections into tabs:

<img width="992" alt="Screen Shot 2022-03-04 at 2 21 01 PM" src="https://user-images.githubusercontent.com/101482/156844507-f8cf400c-d3ba-4efc-a3dc-d47f2b555308.png">

---

<img width="992" alt="Screen Shot 2022-03-04 at 2 21 12 PM" src="https://user-images.githubusercontent.com/101482/156844548-dc255e65-5682-430a-a32f-f3799093472a.png">

---

<img width="992" alt="Screen Shot 2022-03-04 at 2 21 25 PM" src="https://user-images.githubusercontent.com/101482/156844561-ed58b8c5-49cc-437d-a9ab-b85edb705b40.png">

---

This arrangement would make things less cluttered and provide a better foundation for adding new user-specific features in the future (just add a new tab, or add fields to a current tabbed section) without creating an long, unwieldy page.

**Comment by corylown** [comment]
Relates to #156

**Comment by ggeisler** [comment]
@marlo-longley Good question. I would suggest "Cancel" takes the user to the previous page they were on. The current edit profile form has a "Back" link that does this. So the "Cancel" would use the same behavior as the current "Back."

A possible hitch with this is the new layout includes multiple tabs. So if the user completes a change in the first tab, say, and then goes to another tab in the profile and selects "Cancel" where does the user go? I think either back to the previously completed tab, or to the page they were on before going to the Edit profile section, are acceptable. Whichever works best with new code should be fine.
