### ISSUE TITLE
Data contributors want a way to try out sending data to POD

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#455]
It was initially suggested at POD Tech that we set up a separate instance of the application for this. However, we might prefer to provide this functionality through the production application. Maybe we allow for tagging a stream as a `draft`.

**Comment by thatbudakguy** [comment]
what would be the difference between draft and non-default streams? i assumed that the ability to have multiple streams but designate one as default was added for this use case, honestly

**Comment by corylown** [comment]
Yeah, I think the existing streams functionality can be used for this purpose. Maybe we can add some documentation to the wiki to this effect.

**Comment by corylown** [comment]
Documented a suggested way of sending test data to a non-default stream: https://github.com/pod4lib/aggregator/wiki/Uploading-data-using-the-API#testing-sending-data-to-pod
