### ISSUE TITLE
label total row in organizations table

### ISSUE THREAD

**Issue by thatbudakguy** [pod4lib/aggregator#466]
right now the blue row at the end of the organizations page shows totals, but it's not obvious that's what it does, especially if there's no data in the instance:

![Screen Shot 2022-03-10 at 14 54 29](https://user-images.githubusercontent.com/4924494/157768654-15b30a9c-a76e-4b0a-91c9-5baf5b5a7e0c.png)

**Comment by ggeisler** [comment]
Closing this since with the reorganization of the Providers page this table no longer contains this row.
