### ISSUE TITLE
Discuss with POD Tech aggregator app data handling model and contributor norms.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#469]

**Comment by JohnMarkOckerbloom** [comment]
Topics for discussion based on our last call with Index Data include:
   * What should go into a default stream (our expectation, as represented now in our draft docs, is that default streams should always include a full dump, and should generally not include a second full dump unless all deletes from the first dump are also recorded)
   * When should streams be declared default (probably best practice not to do so until there's a full dump available; and it might also be good to hold off until it has been successfully processed, if that's easy to detect)
   * How often should full dumps occur (it's a problem if it's more than once a quarter, unless the POD aggregator can implement an OAI-PMH model that doesn't require harvesters to start from scratch when a new default dump is designated
   * Any issues about file packaging, encoding, and upload procedures that seem to be in doubt or problematic (the development team and folks who worked on the MVP probably know those better than I do-- please comment about any relevant ones)

With these norms in mind, and the conversations we've had with Index Data, the development project should also consider how OAI-PMH service will be provided (both Sebastian and Tom implied that the institution-specific set model  I discussed in the OAI issue would be notably preferable to the stream-specific set model discussed there), and how file normalization and other processing might need to be adapted to best support that model.

**Comment by JohnMarkOckerbloom** [comment]
(Also: It's not one of the contributor norms, but if there's time, it might also be worth touching base with the POD Tech community to see if any of the partners are planning to *consume* POD data for applications or research during this work cycle, and see if they have any expectations about how they're doing it, and if they're hoping to use OAI, ResourceSync, informal file download, or something else.)
