### ISSUE TITLE
Is there a need for a user role that is not affiliated with an organization?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#483]
I think the answer may be no, especially if we add support for organizations that are data consumers only.

**Comment by JohnMarkOckerbloom** [comment]
If we're limiting data consumption to specific organizations, then it makes sense that all users who can consume data have to be affiliated with an organization.  However, I don't know if we want to assume that limitation all the time; it might make it harder to use our data that we want to.  So I'd be wary about designing a system where users *must* be affiliated with an organization.  (It's okay if the usual way to request and create users is via an organization, however.)

**Comment by anarchivist** [comment]
From the 2022-03-18 POD management call: we have confirmed that there is not a need for a user role that is not affiliated with an organization. 

Organizations are understood to be "any entity with > 1 person that's authorized to interact with the POD Aggregator."
