### ISSUE TITLE
Harvard: the count of unique records is smaller than the number I actually sent

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#490]

**Comment by corylown** [comment]
Closing because I think this is resolved. The observed delete behavior is what is expected for records with a `d` in position 5 of the leader.

**Comment by cbaksik** [comment]
Yes, thank you for helping to troubleshoot this issue. FWIW, each ILS has its own internal way of deleting records from its database, so the presence of a 'd' in this byte often has no effect locally, so sometimes they are there and folks don't realize. I found a few hundred and will be doing clean-up.
