### ISSUE TITLE
What roles (org admin, superuser) should manage org info and contact info?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#492]

**Comment by ggeisler** [comment]
What are the arguments against:

- Org admin has read/write on all organization management tasks, for their associated organization
- Superuser has read/write on all organization management tasks, for all organizations

Where organization management tasks are the tasks in the "Organization page - Organization management" section of the spreadsheet.

The second item assumes we make Superuser assignments very selective (i.e., probably fewer Superusers than we currently have POD admins).

That's been my working assumption so just curious what drawbacks to that model might be in people's minds.

**Comment by JohnMarkOckerbloom** [comment]
I'm in agreement with @ggeisler here.  Unless it poses significant difficulties to implement, or introduces unacceptable risks or downsides, I'd say let org admins do pretty much anything possible with their organization, but not with other organizations.  There may be particularly risky or sensitive operations on a particular organization that should be limited to superusers, but none of the operations currently in the "Organization management" section of the spreadsheet strike me as that way (except that it might be good to prevent an org admin who's not a superuser from revoking their own access or account, if that's not hard to implement.)

**Comment by JohnMarkOckerbloom** [comment]
To my comment above, I'll add the caveat that org admins who aren't superusers might still need to be restricted from removing streams that are or have recently been default, per issue #489.

**Comment by marlo-longley** [comment]
Related to #634

**Comment by marlo-longley** [comment]
@corylown I feel like this ticket has either been resolved, or morphed into more specific tickets after Gary's redesign. I also opened a couple today that might supersede this. I would vote to close this.

**Comment by corylown** [comment]
@marlo-longley makes sense. I'll close it.
