### ISSUE TITLE
Adjust details of user menu in topbar

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#496]
Several issues of varying importance I noticed:

- If you aren't an admin, we show an extra menu divider (which we do need when you are an admin):

<img width="358" alt="Screen Shot 2022-03-21 at 11 49 10 AM" src="https://user-images.githubusercontent.com/101482/159345094-2743793c-9a85-48e7-a3af-01c63c68debb.png">

- I forget if this is adjustable via a Bootstrap class or not, but it feels odd to me that the menu items are aligned on the opposite side from the icon you use to display the user menu. In other words, is it possible to right-align the menu so that it drops down directly below the icon?

<img width="435" alt="Screen Shot 2022-03-21 at 11 47 49 AM" src="https://user-images.githubusercontent.com/101482/159344419-d916d3e6-e9d0-4acf-ada6-21b8572ff686.png">

- The dark background of the menu with the gray text: not sure whether it is accessible contrast or not (I'll look at accessibility details later) but visually it looks muddy to me. I think a white background menu would work better. Since we do have plans to reevaluate the application color palette separately, we could wait on this, but I'm pretty sure a light background menu will work with whatever do change the topbar background color to.

(For the last two items, look at Github's equivalent user menu in the topbar, which basically does what I'm suggesting for both of those.)

- Also, maybe this needs to be a product owner decision (@JohnMarkOckerbloom), but since we don't currently require a registered user to have provided a name, I'd suggest we only display the email address as the user menu link (as in the first screenshot in this comment). That would take up less space in the topbar while providing more consistency between users with provided names and users without, and I personally don't see the need to show the user's actual name versus their email address.

**Comment by cbeer** [comment]
> The dark background of the menu with the gray text: 
![Screen Shot 2022-03-21 at 12 35 56](https://user-images.githubusercontent.com/111218/159350394-d6f8ebc9-9879-450d-ba39-cba00850227b.png)

**Comment by ggeisler** [comment]
Yeah, I wasn't sure it wouldn't pass, but it feels muddy to me nonetheless, so more of a visual design issue than an accessibility one. But I'm fine with not worrying about it until we do an overall visual design update.
