### ISSUE TITLE
Users should belong to a single organization

### ISSUE THREAD

**Issue by thatbudakguy** [pod4lib/aggregator#503]
#501 makes this somewhat simpler from the UX side, since now the only avenue for creating new users is having an organization admin invite them, which will automatically add them to that organization.

see also discussion on https://github.com/pod4lib/aggregator/issues/483

the primary use case for this is developer-facing; it allows us to radically simplify the user-organization relationship. instead of a polymorphic relationship through `Role`, each `User` now has exactly one `Organization`, and is either an admin or not.

to enforce this, I think we need to:

- [ ] remove `controllers/site_users_controller.rb`, which i think is related to organization-less users
- [ ] remove `models/Role.rb` since we no longer need polymorphic roles tied to any resource
- [ ] add a simple `is_admin` flag to User and a corresponding `is_admin?` check that can be used in `models/Ability.rb`
- [ ] modify `Organization` so it `has_many :users, inverse_of: :organization`, so we can query both `User.organization` and `Organization.users` (maybe?)
- [ ] remove the existing implementation for `User.organizations`
- [ ] remove rolify, since it's no longer needed

**Comment by thatbudakguy** [comment]
i think so far we haven't been able to come up with any exceptions, but if you can think of some that'd be useful to discuss. we confirmed in https://github.com/pod4lib/aggregator/issues/483 that users must have an organization, and thus far the only use case for multiple membership is so that you can see things in another org, which is resolved by #502.

re: super admins, see #502.

**Comment by corylown** [comment]
I'm closing this issue. We've left the underlying model in place to allow users to belong to more than one organization if needed, but this is largely hidden via the UI and in some places for view purposes (such as the home page) we assume a user belongs to a single organization (calling `.first` as needed).
