### ISSUE TITLE
Prevent deletion of the default stream

### ISSUE THREAD

**Issue by thatbudakguy** [pod4lib/aggregator#505]
_As an organization admin, I want the default stream for my organization to be protected from deletion so that it can’t accidentally be deleted._

see discussion on #489.

implementation notes:

- [ ] update `StreamsController#destroy` to check if the stream being deleted is the default, and if so, deny the request. the response code might be 400 or 403, although evidently 423 ("Locked") is also a thing.
- [ ] remove the UI option/button to destroy the default stream in `views/streams/index.html.erb`

**Comment by cbeer** [comment]
Instead of doing the check in the controller, I think we can and should add the check in `Ability` (and get the UI piece for "free").
