### ISSUE TITLE
Dartmouth: their org has two default streams

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#510]
<img width="991" alt="Screen Shot 2022-03-25 at 1 04 55 PM" src="https://user-images.githubusercontent.com/458247/160168082-b6f5f17f-68f8-423a-a580-53dea9c83acf.png">

**Comment by thatbudakguy** [comment]
I can't replicate this in production; there's only one default stream (confirmed through console) and it's named like in the screenshot. The screenshot is odd since it seems to list the same stream twice...

**Comment by corylown** [comment]
There were two default streams with the same name but different identifiers. We'll need to keep an eye on this. I think the duplicate is now named `2022-03-25 - 2022-03-26`

**Comment by corylown** [comment]
I'm going to close this for now since the issue seems to have gone away, but let's keep an eye on it.
