### ISSUE TITLE
Should organization contact email address be a single-valued, required field?

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#515]
Currently we allow an organization to add more than one contact email address but it is optional.

I realize we're still ramping up to realistic use of POD but as we move towards real production in this workcycle I wonder if we can look at this field again. Specifically, it seems to me that it is not unreasonable to:

- **Make contact email address a required field**. Since POD users will be able to look at other providers files, etc. it seem reasonable that a POD user might have a question for a given provider about their data. They should have a clear way to ask their question of the appropriate person/mailing list at the organization.

- **Change contact email address to a single-valued field**. Providing multiple email addresses will pose a challenge to putting the contact email address in a prominent location in the upcoming redesign, but just as importantly, requiring the organization to choose a single email address seems like a good way forcing the organization to think about how they want to handle POD-related requests (i.e., creating or using an existing mailing list rather than just adding a bunch of people and making the POD user with a question try to decide which one to email or to email everyone, etc.).

For reference, I believe that currently only Stanford and Yale have provided a contact email address. Stanford is pointing to a single mailing list, while Yale has listed two individual email accounts.

And here is the proposed page header where the contact email address will be more prominently displayed:

<img width="1197" alt="Screen Shot 2022-03-28 at 1 46 24 PM" src="https://user-images.githubusercontent.com/101482/160488268-985b6cc6-f68f-49f0-9434-92f974a0d554.png">

**Comment by ggeisler** [comment]
@JohnMarkOckerbloom Thanks for the comments. The actionable steps I take from this are:

- You will verify that organizations are willing to provide one, and only one, contact email or link (I don't know how we should balance "asking" versus "informing"; I think this is something we **should do** unless someone has a really good reason not to, rather just a casual "we'd rather provide multiple emails")
- I'll ticket an update for the UI that displays the contact info so it is displayed as a link (to either an email address or a URL)
- I'll include relevant updates to the form used for managing the contact info (you don't currently see it from the Edit org page because it is in a section at the very bottom of the main org page; but that's been updated in the new redesign plan)

As you said, non-logged in users only see the homepage and we don't plan to display the contact address for an organization there, so there's no issue with non-POD users seeing this.

**Comment by JohnMarkOckerbloom** [comment]
Thanks!  I'm thinking the best way to touch base with our providers is to send an email to the pod-tech list (since I suspect more people read that that are on the Slack instance or follow Github issues).  I'll plan to draft and send out something later today or tomorrow.

**Comment by JohnMarkOckerbloom** [comment]
Per today's post-standup conversations:
   * A contact address or link will be expected for all provider organizations, though its absence will not block organization creation.
   * The ability to specify or change contact info will be included on a form for editing organization information
   * Once that form is available, and the org owner role is established (as distinct from POD aggregator application administrator) and supported in the interface, I'll send out a note to pod-tech asking for providers to fill out that information, and pointing to where they can do so.  In some cases, provider organizations may need to designate an org owner before they can edit the form.

**Comment by corylown** [comment]
See #544

**Comment by thatbudakguy** [comment]
the implementation work for this is done, although as @corylown noted on #667, a contact email is currently required to create a new organization.

i think we're ready to ask organizations to provide an email if they haven't yet (although maybe we want to wait until #638 is complete so that there's less likelihood of confusion around the owner role).

**Comment by corylown** [comment]
@thatbudakguy I think we can close this issue. I'll open a new issue to address whether a contact email is a hard requirement to create an organization. I think it should not be.
