### ISSUE TITLE
Create new Data page and link from topbar nav and homepage

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#517]
I believe our goal is to provide a page that is a clear destination for users who are specifically interested in consuming data (rather than our current approach, which requires a data consumer to find what they want through the Organization pages).

Below is a mockup of the Data page, although this is really more to convey the idea than the exact content. I don't know what the use cases for data consumers are so am not certain what all should be part of this page. I think we could create this page now and link it up to the new navigation and homepage, but we will probably want to populate it with the appropriate content over time as we learn better what data consumer use cases are.

<img width="1195" alt="Screen Shot 2022-04-11 at 2 34 03 PM" src="https://user-images.githubusercontent.com/101482/162837386-c379c565-5224-4b4e-b86c-4728e3d17fca.png">

- This Data page is linked for any logged-in user via the "Data" navigation item in the topbar, as described in #470. In addition, in #470 I suggest the "POD Data" section below the hero block also link to the Data page.

- The Data page should not be accessible to anyone not logged in to POD.

I'll put a Question label on this ticket to encourage people to add use cases and ideas for what should go on this page to comments below.

**Comment by cbaksik** [comment]
Page should include text of or link to the data re-use agreement. Currently it's in a [Google doc](https://docs.google.com/document/d/1EZG7z_A13jxPfHbYhT7Ae4Ays10fhecqfoGJhqrcjD8/edit?usp=sharing) but should probably be elsewhere.

**Comment by ggeisler** [comment]
@cbaksik This sounds like a good idea to me. I've updated the mockup above to include an initial section to represent the general idea. I think someone (perhaps @JohnMarkOckerbloom ?) probably should give some thought to exactly what we want to present here and how it relates to other data use related documentation, such as the Google doc you linked to. For example:

- Should that Google doc be converted to a page in the application wiki? That would feel more integrated and seems more sustainable/flexible than linking to a Google doc.
- Alternatively, the entire contents of that Google doc could be included in the new Data page, perhaps in a section collapsed by default but could be expanded by the user if they wanted to read the details.

**Comment by JohnMarkOckerbloom** [comment]
I agree there should be a link to the Data Provider and Usage Framework from the Data page.  At some point, I think it would be good to have the Framework in our own space (I'd recommend the wiki, since that's easier for more people to update than the application itself is), but until it's finalized it should probably stay where it is.  (I'm not sure it's finalized, since among other things, I don't yet see endorsements from Columbia or MIT.  I can ask a board member about this the next time I see one, though, or they're in a meeting.)

**Comment by corylown** [comment]
Closed via #593
