### ISSUE TITLE
Customize org section on homepage

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#519]
The new homepage design in #470 suggests adding a full-width section just above the footer that will either:

- Offer a Login button and a contact link, when the user is not currently logged-in
- Display a summary of the user's organization status with some quick links to tasks/pages, when the user is logged-in

## Public user (user not logged-in)

<img width="1196" alt="Screen Shot 2022-03-30 at 9 51 43 AM" src="https://user-images.githubusercontent.com/101482/160889798-6207dc3c-0304-436d-965b-6dc19746f1c3.png">

- [x] All elements in this section should be centered in the section
- [x] `Already a POD user?` as an `<h2>` with a `.h3` class (at least to start)
- [x] Login button - takes the user to the same page as the "Login" link in the topbar
- [x] `Interested in using POD data?` as an `<h2>` with a `.h3` class (at least to start)
- [x] `Check out the POD wiki or contact someone@institution.org` where the "POD wiki" link is to https://github.com/pod4lib/aggregator/wiki and the email link is TBD (perhaps @JohnMarkOckerbloom can suggest what the main contact email address for the project should be, or decide if we don't want to offer that here)

## Org member (Provider org)
When a user is logged-in, we know the organization they're associated with so can present some customized info in this section:

<img width="1196" alt="Screen Shot 2022-03-30 at 9 48 07 AM" src="https://user-images.githubusercontent.com/101482/160896796-780c674d-d32b-457a-8eb3-f43a236bcdee.png">

**A:**
- [x] Organization name (and logo image, if it exists) as an `<h2>` with a `.h3` class (at least to start)
- [x] `Most recent upload was on [date and time]` - using last upload info for that organization

A new row below the org header/text. Three columns; we might have to do some trial and error to see how they lay out with real data to decide how much left and right margin to give the row and when the columns should take full width at smaller breakpoints. I can help with that if necessary when the basic code and real data is in place.

**B:**
- [x] `Latest uploads` as an `<h3>` with a `.h4` class (at least to start)
- [x] List of the the filenames of the last three files uploaded by the organization, along with their file status icon, following the pattern we're using in #508. Filenames should not be linked here, I don't think.
- [ ] `View all stream files ...` as a link to the provider page, default stream, Files tab.

**C:**
- [x] `Processing status` as an `<h3>` with a `.h4` class (at least to start)
- [x] Assuming the org has some jobs actively processing or with non-completed (non-error?) status, show a line for each distinct status (not including the completed status, I think? we don't want this list to be too long is my concern here; we can see how it looks with real data and adjust the details as necessary), with the count of jobs matching each status. Use the same icons we use in the processing status table (#317).
- [ ] `View status details ...` as a link to the provider page, default stream, Processing status tab.

**D:**
The actions we list here can be updated over time as we figure out what might be best 3 or 4 links for users.

- [x] `Quick actions` as an `<h3>` with a `.h4` class (at least to start)
- [x] `Upload file` as a link that takes the user to the same page as when they use the "Upload file" button on the  stream page (`\uploads\new`)
- [ ] `View default stream` as a link to the provider page, default stream, Files tab
- [x] `View organization details` as a link to the provider organization page

### Status when no jobs processing
Section "C" above assumes the organization has some active or non-completed jobs. If instead the organization has no jobs processing and no problem jobs, we could just show a single line with the success icon and `No active jobs`. Below that show the same `View status details ...` link to the provider page, default stream, Processing status tab.

<img width="1196" alt="Screen Shot 2022-03-30 at 9 49 19 AM" src="https://user-images.githubusercontent.com/101482/160893060-0f16b959-0418-419e-869f-1fb82d00a605.png">

## Org admin (Provider org)
If the logged-in user is an organization admin, the section is almost identical to what is suggested above, except:

- [x] Change the last link under "Quick actions" to `Manage organization`, since the org admin can actually edit those pages.

<img width="1196" alt="Screen Shot 2022-03-30 at 11 16 12 AM" src="https://user-images.githubusercontent.com/101482/160903757-79cab681-99fb-4426-ac4b-e1e124b13c1f.png">

## Org member (Consumer org)
When the logged-in user is a member of a consumer, rather than provider, organization, most of the info suggested above doesn't apply. Until we better understand the data consumer use cases, I'm not certain what should go in this section but at the very least we can start with some links that are most relevant to the data consumer. As we improve the Data page (#517) we'll probably get some ideas about what should go in this section.

<img width="1196" alt="Screen Shot 2022-03-30 at 11 14 39 AM" src="https://user-images.githubusercontent.com/101482/160903501-2907be76-7b5b-4884-b632-da30be2c9498.png">

- [ ] `Harvest data` as a link to the new Data page
- [x] `Data consumer documentation` as a link to https://github.com/pod4lib/aggregator/wiki/Harvesting-using-ResourceSync
- [x] `View organization details` as a link to the provider organization page

## Org admin (Consumer org)
If the logged-in user is an organization admin, the section is almost identical to what is suggested above, except:

- [x] Change the last link under "Quick actions" to `Manage organization`, since the org admin can actually edit those pages.

<img width="1196" alt="Screen Shot 2022-03-30 at 11 08 28 AM" src="https://user-images.githubusercontent.com/101482/160904122-031039f8-583a-49e0-bd83-8ec01dabfd47.png">

**Comment by anarchivist** [comment]
We've settled on the preferred contact email address to start - that should be `pod-support@lists.stanford.edu`. (cc @thatbudakguy; will leave the same comment on your WIP PR.)
