### ISSUE TITLE
Remediate (or remove) POD users with no organization

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#520]
The new design for the homepage [includes a customized section](https://github.com/pod4lib/aggregator/issues/519) with content that is based on the user's organization.

However, because there is currently (or was) a way for users to register directly, and that path doesn't associate the user with an organization, our list of current POD users includes some that don't have an associated organization. I think violates the rule we want to have going forward that every POD user belongs to one organization.

We should remediate (or remove) the existing POD users with no associated organization. Otherwise, we'd have to have some additional handling of the org section on the homepage to deal with users with no organization.

I suspect it would probably be pretty easy to look through the (presumably very short) list of users with no organization and figure out which org to add them to. For any where it isn't obvious, I guess we could send them an email and ask who they are and who they work for, and either associate or remove them from POD depending on their answer?

**Comment by corylown** [comment]
Users without any organization affiliation have been remediated. I deleted a few that I couldn't identify but mostly just added them as members to their org:

```
3.0.0 :074 > User.all.select { |u| u.organizations.empty? }
 => [] 
```
