### ISSUE TITLE
Remove inter-stream deletes from resource lists and the normalized files list.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#522]
Decided in meeting on 3/30/22 with @anarchivist & @JohnMarkOckerbloom that we're going to remove the inter-stream delete deltas from the resource lists.

We will leave the existing `removed_since_previous_stream` method in place but will not expose the generated file via the UI.

Places where this needs to be removed:

- https://github.com/pod4lib/aggregator/blob/main/app/views/streams/show.xml.builder#L12-L14
- https://github.com/pod4lib/aggregator/blob/main/app/views/streams/normalized_dump.xml.builder#L14-L16
- https://github.com/pod4lib/aggregator/blob/main/app/views/streams/_normalized_dump.html.erb#L13

**Comment by JohnMarkOckerbloom** [comment]
It also needs to be removed from some of the documentation (e.g. there are some places mentioning the feature in https://github.com/pod4lib/aggregator/wiki/Harvesting-using-ResourceSync ).  I can take the relevant bits out later today.  (There may be other spots I haven't found yet.)
