### ISSUE TITLE
Replace "Organizations" page with "Providers" page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#523]
As part of the redesign, we're updating the "Organizations" link in the topbar to be "Providers." The page that links points should now include one section from the current `/organizations` page and one section from the current `/dashboard/uploads` page:

<img width="1020" alt="Screen Shot 2022-03-30 at 4 05 45 PM" src="https://user-images.githubusercontent.com/101482/160945422-6a3b1a6c-e0a9-4930-8d17-e43d9bc799bf.png">

The suggestions below assume we're using the current Organizations page as the basis for the new/revised page.

**A:**
- [x] Rename the current `<h1>Organizations</h1>` to `<h1 class="visually-hidden>Provider statistics</h1>` (note the added CSS class; I think we can hide the h1 but we still need it in the page for proper heading structure)
- [x] Add an `<h2>` with the label `Aggregated uploads from providers`
- [ ] Move the upload graphs from the current `/dashboard/uploads` page to this section
 

**B:**
- [x] Add an `<h2>` with the label `Upload statistics by provider`
- [x] Include the current providers table in this section
- [x] Right-align the Files, Size, Unique records, and Total records columns
- [x] Remove the "d" from the "Last updated" column header
- Note that the mockup shows a simpler date display format than the current table. That can be handled later when we figure out an answer to my comment in #509
- [x] Remove the totals row currently at the bottom of this table (we'll show the records totals on the homepage)
- [x] Ensure only superusers see the Edit and Destroy buttons at the end of each row (this doesn't seem like the best place to offer the Destroy action -- too easy to do -- but dealing with that could be a separate ticket) 
- [x] Ensure that only superusers see the New organization button (not shown in the mockup)

Note that I've removed the Harvesting table that is at the bottom of the current Organizations page, assuming it makes more sense on the new Data page.

**Comment by marlo-longley** [comment]
Table column text alignment relates to #426

**Comment by marlo-longley** [comment]
After discussion we decided for now to leave the route as `/organizations` rather than changing it to `/providers` - could possibly change this later
