### ISSUE TITLE
Story: Reorganize the Provider page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#527]
A significant change to the application the team agreed on was to reorganize the contents of the Provider page (what is currently the "Organization" page) into several distinct pages that share a common header section. The header section will include tabs to navigate between the individual pages. This will enable the user to see all provider-related content and tasks without having to scroll to the bottom of what is sometimes a long page:

<img width="1062" alt="provider-page-updates 5" src="https://user-images.githubusercontent.com/101482/161166232-21ea4bf8-f2f2-4e48-85ed-b428eae8aee4.png">

---

Because there are a lot of updates involved, it'll probably be easier to work on in smaller tickets. So this is a just a story ticket intended to group the more actionable tickets related to the reorganization of the Provider page.

- [x] #528
- [x] #529
- [x] #530
- [x] #531

**Comment by corylown** [comment]
I believe this is complete since the related issues have been closed.
