### ISSUE TITLE
Set up tab navigation for main provider-related pages

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#531]
Related to #527.

<img width="1062" alt="provider-page-updates 4" src="https://user-images.githubusercontent.com/101482/161166816-4c911987-ae6b-44dc-badf-a55ce02025dc.png">

---

The provider page currently contains several distinct chunks of stream-related information that would benefit from being more clearly distinguished from each other, so the user can focus on the chunk of information most relevant to their current task.

The goal is to create a tabbed navigation to enable the user to see these distinct chunks of stream-related information and easily move between them. 

- [x] The tabs container should be horizontally-centered on the page, below the new container with the stream file and record counts.
- [x] We can experiment with styling, though I'd suggest trying `.nav-pills` to start. 
- [x] The order and label of the tabs is: `Files`, `Normalized data`, `Processing status`, and `Profile`.
- [x] "Files" is the default tab/page when the user selects links elsewhere on the site for a specific Provider's page.
- [x] The "Processing status" tab should not be displayed to a user who is an org member or org admin and is looking at the provider page of an organization not their own. (A user acting as a superuser should see all tabs regardless of their organization affiliation.) Example: I'm a Stanford user looking at Duke's provider page:

<img width="1062" alt="Screen Shot 2022-03-31 at 4 24 48 PM" src="https://user-images.githubusercontent.com/101482/161166930-4fda155e-e050-47f7-8e0c-962baf52180b.png">

---

## Examples
I'm not sure if we need a separate ticket for this, but for reference these are the chunks of information that go with each tabbed page:

### Files
The current stream files table, but without the totals row:

<img width="1062" alt="Screen Shot 2022-03-31 at 4 18 34 PM" src="https://user-images.githubusercontent.com/101482/161166855-725ef853-0fec-4f18-b98b-f598771d6e72.png">

---

### Normalized data
The normalized data section of the current provider page (we might reformat the table differently, but that would be a separate issue):

<img width="1062" alt="Screen Shot 2022-03-31 at 4 18 44 PM" src="https://user-images.githubusercontent.com/101482/161166872-117b47ba-a889-4848-b4e3-a155d942a844.png">

---

### Processing status
Just the processing status info. There is an [existing ticket about displaying this in a new way](#317).

<img width="1062" alt="Screen Shot 2022-03-31 at 4 18 53 PM" src="https://user-images.githubusercontent.com/101482/161166886-f321ca92-0257-48cc-97ce-737976b33e03.png">

---

### Profile
This is the content of the page (`/streams/[name]/profile`) you currently get to by selecting the magnifying glass icon in the files totals row (first row of the table):

<img width="1062" alt="Screen Shot 2022-03-31 at 4 18 59 PM" src="https://user-images.githubusercontent.com/101482/161166912-819a1697-2ab1-4c4f-b2a2-18812f02108e.png">

---

**Comment by cbaksik** [comment]
Would like "Files" tab to read "Uploaded files" to distinguish it from Normalized data which is also a list of files. 

Would like "Profile" tab to be "MARC analysis" (or "MARC profile") to distinguish it from Profile as used elsewhere in the site (where it refers to Org profile).

**Comment by ggeisler** [comment]
@marlo-longley We discussed this in the design walkthrough for Harvard meeting and agreed with @cbaksik's suggestions. I won't try to update the mockups in the ticket but the changes would be:

- `Files` tab label becomes `Uploaded files`
- `Profile` tab label becomes `MARC analysis`
