### ISSUE TITLE
Columbia: cannot get upload-by-URL to work

### ISSUE THREAD

**Issue by bobpersing** [pod4lib/aggregator#533]
From Stuart Marquis (marquis@columbia.edu):

The documentation says that there are two ways to upload content - by attaching files to the POST call, or by simply passing a URL parameter, and leaving it to POD to download the file from the URL.  I'd like to use the second method.
    [https://github.com/pod4lib/aggregator/wiki/Uploading-data-using-the-API](https://github.com/pod4lib/aggregator/wiki/Uploading-data-using-the-API)

Unfortunately - all I'm getting back from the API is a "400 Bad Request".  
The code is simple:

```perl
my $ua = LWP::UserAgent->new;
my $req = HTTP::Request->new(POST => $pod_url);
$req->header('Authorization' => "Bearer $access_token");
$req->content("file[url]=$upload_url");
my $response = $ua->request($req);
```

With debugging turned on, this is what's getting sent, and what's coming back.

```
-->
POST [https://pod.stanford.edu/organizations/columbia/uploads]
Authorization: Bearer [redacted]
User-Agent: libwww-perl/5.833

file[url]=https://lito.cul.columbia.edu/extracts/ColumbiaLibraryCatalog/POD/extract-001.xml

<--
HTTP/1.1 400 Bad Request
Connection: close
Date: Tue, 29 Mar 2022 20:35:56 GMT
Via: 1.1 [lito-squid-prod1.cul.columbia.edu]
(squid/3.5.28)
Server: Apache/2.4.6 ()
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Client-Date: Tue, 29 Mar 2022 20:35:56 GMT
Client-Peer: [128.59.241.60:3131]
Client-Response-Num: 1
Status: 400 Bad Request
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Cache: MISS from [lito-squid-prod1.cul.columbia.edu]
X-Cache-Lookup: MISS from [lito-squid-prod1.cul.columbia.edu:3131]
X-Powered-By: Phusion Passenger(R) 6.0.12
X-Request-Id: 3b8c77fe-09ac-4891-aa4d-5d5a231fec77
X-Runtime: 0.024103

(no content)
```

I know I'm posting to the correct API URL, because the URL works in a browser.
And I'm sure that the file URL I'm passing is available.
I know I'm using the correct token, because when I pass an invalid token I get a different error (500).

I've tried passing the content both unescaped and escaped, and it makes no difference - both give me a 400 error.

I've tried adding a "stream" param, both in the content, and appended to the URL as in the examples.  No difference.

Does the upload-by-URL feature work?  Are there examples of other partners using this?

**Comment by anarchivist** [comment]
@bobpersing  It looks like Stuart may be using the wrong parameter here: rather than `file[url]`, it should be **`upload[url]`** as described in the documentation.

**Comment by bobpersing** [comment]
Yup, that was the problem -- thanks.
