### ISSUE TITLE
Content security policy for charts is wrong

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#538]
Discovered in the course of working on #537 and implementing charts. This issue is currently reproducible on the live site.

I followed the existing pattern from the dashboard controller, and [documented in the Chartkick docs here](https://github.com/ankane/chartkick/blob/master/guides/Content-Security-Policy.md)

```ruby
  content_security_policy do |policy|
    policy.style_src :self, :unsafe_inline
    policy.script_src :self, :unsafe_inline
  end
```

This works properly when the page first loads, but when navigating away and coming back, the security policy is violated, and the charts to not load. Steps to reproduce:

1. Navigate to a page with the charts (previously "Activity", after merge of #537, "Providers"). View (no errors):
<img width="1683" alt="Screen Shot 2022-04-01 at 17 24 12" src="https://user-images.githubusercontent.com/1328900/161343237-5bab2b40-9c5b-4b7f-a4f1-20d4d7d23795.png">

2. Click away from the page, say to on one of the links to a specific provider
3. Hit back to the charts page. View (errors):
<img width="1692" alt="Screen Shot 2022-04-01 at 17 27 50" src="https://user-images.githubusercontent.com/1328900/161343558-6e9fc709-8cbc-4782-b0ab-6dc598e61e68.png">

**Comment by thatbudakguy** [comment]
i think if we're doing a nonce we don't need `unsafe-inline` (as the console error says). the [rails docs on setting up a nonce](https://edgeguides.rubyonrails.org/security.html#adding-a-nonce) might be helpful. i think we already use the `csp_meta_tag` in the `<head>` so might just need to look at where we're including the script
