### ISSUE TITLE
Update the Manage/View organization users tab/page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#539]
Related to #534.

There are two parts to this:

- Change the current structure of the Organization Users list to a table (so we can display the different user attributes better)
- Ensure that when this new table is viewed by org members (rather than org admins/superusers), the edit components are not available

## Change the current structure of the Users list to a table
Organization users are currently displayed in a list, within a Bootstrap card component. Here's how I suggest they should be displayed (this is what the **org admin/superuser** sees):

<img width="1198" alt="Screen Shot 2022-04-04 at 2 14 29 PM" src="https://user-images.githubusercontent.com/101482/161633534-cb575055-de17-48fd-aa0d-bf547da2dd1f.png">

---

- [x] Remove the Bootstrap card component the user-related elements are currently part of. That made sense when we were showing a lot of different things on the same page, but now that we're focusing each page on a single thing, there's no need for the extra borders and header of the card component.
- [x] **A:** Use the existing "Invite" button but position it directly below the page heading "Manage users", left-aligned in the content area
- [x] **A:** Re-label the Invite button `Invite new user to organization`
- [x] **B:** To display the user data, switch to a table layout from the current unordered list
- [x] **B:** Break out each user field to its own column. The mockups in this ticket reflect our current state where every user has an email address but name and title are optional.
- [x] **B:** Add a new column "Role" with the user's role (`Member` or `Admin`). (We don't currently show this in the org user list, but I think it could be handy for org users to see whose in their org is an admin, in case they need some admin-only actions to be taken.)
- [x] **C:** Create a final column labeled `Actions`. Move the Remove buttons to this column, centered in the column, and change the label to `Remove user`.

## Ensure page is read-only for non-admins
If the user is an org member, the page should look more like this:

<img width="1198" alt="Screen Shot 2022-04-04 at 2 16 01 PM" src="https://user-images.githubusercontent.com/101482/161633560-01997e07-527c-4382-8b4d-52e7d075e203.png">

---

Where we:

- [x] Don't display the Invite button
- [x] Don't display the Actions column and its Remove user buttons

I believe all of the above is the same whether the organization is a provider or consumer-only; no special case for consumer-only on this page.

**Comment by cbaksik** [comment]
Do we want to add a field for pronouns?

**Comment by ggeisler** [comment]
> Do we want to add a field for pronouns?

I'm certainly not opposed to it but I wonder if it is necessary or appropriate since the application isn't intended to provide a way for a user to communicate with another user; displaying user names in this context is just to identify which people in the organization have accounts, and I'm not sure preferred pronouns add to that? (I sort of have the same thoughts about "Title".) I can be overruled, though, if it seems useful to others.

**Comment by marlo-longley** [comment]
My take is that we can discuss it and potentially add the pronouns field, but since this ticket is already pretty big, we should break the question out into a new ticket if we want to proceed.
