### ISSUE TITLE
Update the Manage/View organization Access tokens tab/page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#541]
Related to #534.

<img width="1185" alt="Screen Shot 2022-04-04 at 2 42 25 PM" src="https://user-images.githubusercontent.com/101482/161638724-c4607d83-1374-4a44-81f2-86b43e5022cb.png">

- [x] Remove the Access tokens card currently in the Organization management section at the bottom of the organization page. All this currently does is provide the user with a link to a dedicated Manage tokens page, which in the redesign will be available from the Access tokens tab on the Manage/View organization page.
- [x] On the Access tokens tab of the Manage/View organization page, display the current Manage tokens page content, as shown above.
- [x] (Optional, but would be helpful to the user if we have time to do it) Update the current Manage tokens page content mentioned above by adding a new primary button with the label "Copy". This button copies the associated access token string to the user's clipboard, so they don't have to manually copy it from the input.
- [x] If the user is a **org member**, and not an org admin, remove the "Create token" button they currently see (based on our new roles and permissions spreadsheet, only org admins should be able to create new access tokens).

The mockup at the top of this ticket is what the org admin sees. Here's the org member view of the page:

<img width="1198" alt="Screen Shot 2022-04-04 at 2 38 58 PM" src="https://user-images.githubusercontent.com/101482/161638799-33bd2abb-75ed-4bd1-a115-fbbb8f405768.png">

---

### Bonus points:

- [x] Add the `disabled` HTML option to the input with the token value (since the value isn't editable, this will make it easier/more obvious for the user if they copy directly from the input -- unless I'm missing something and the token value should be editable).
- [ ] Add the Font Awesome `copy` icon to the button. We aren't generally following a style of having icons on buttons in the application, but this seems like a special case where it would be useful to give the user an additional hint that the button can be used to easily copy the token value.

The two additions above would make things look more like:

<img width="1137" alt="Screen Shot 2022-04-07 at 4 58 04 PM" src="https://user-images.githubusercontent.com/101482/162338285-4654e3c4-109a-4f7b-976e-b9412032b27b.png">

**Comment by cbaksik** [comment]
+1 for Copy button

**Comment by marlo-longley** [comment]
@ggeisler Thanks for all the details in this ticket! We are now using the Bootstrap Icons library for the app. The closest icon to this Copy one I could find was this:
<img width="235" alt="Screen Shot 2022-04-08 at 11 06 24" src="https://user-images.githubusercontent.com/1328900/162470280-be800b53-0328-4fca-9961-2f0aef40dbdc.png">

Here are all the icons (you can filter in the top right) if there's a different one you prefer
https://icons.getbootstrap.com/

**Comment by ggeisler** [comment]
@marlo-longley Right, sorry, forgot about which icon library we're using (I've got Font Awesome integrated into my Figma setup so I just think in terms of that one). But the BS one you picked looks fine, thanks!
