### ISSUE TITLE
Update the Manage/View organization Provider details tab/page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#542]
Related to https://github.com/pod4lib/aggregator/issues/534.

## Org admin version of the page
The last task in #534 suggests moving the second part of the form on the "Editing organization" page to be the main content below the tabs when the "Provider details" tab is active, as shown below:

<img width="1185" alt="Screen Shot 2022-04-04 at 2 43 22 PM" src="https://user-images.githubusercontent.com/101482/161639337-b461cf0c-4f3f-4684-ab27-f42557f5d375.png">

Because we're splitting the current Editing organization form into two, on this page and the Organization details page, we can customize the label of the submit button on each page. Here:

- [x] Label the submit button `Update provider details`

I think that's all that needs to be done for the **org admin** view of the Provider details page.

## Org member version of the page
We don't currently have a read-only view of this form for org members, but I think it would be useful for at least consistency purposes if the org member can see the values of this form, even if they can't update the form.

So, when the user is an **org member**, instead of displaying the editable form, we could show the current values in a description list:

<img width="1198" alt="Screen Shot 2022-04-04 at 2 37 19 PM" src="https://user-images.githubusercontent.com/101482/161639692-4ef7bf9d-a23e-469a-b80b-cf692e6ce1e0.png">

---

- [x] Omit the submit button in the org member's version of this page.

- [x] Put provider details form fields into a definition list. Use a `dl` element and put the value of each field label in a `dt` and the field value in a `dd`.

- [x] Indicate when a field has no current value. If for some reason there isn't a current value for any field, I suggest we display the string `no value provided` in italics so it's clear what the situation is:

<img width="918" alt="Screen Shot 2022-04-04 at 3 11 40 PM" src="https://user-images.githubusercontent.com/101482/161640633-e78062e3-5252-4866-b0e4-5cee47f8120b.png">

**Comment by cbaksik** [comment]
Not all providers may includeitem-level information. ReShare partners will, but it is likely that POD may expand beyond the ReShare partners, and include partners that do not share item-level information. 

I would like a field to place a URL that will link to a local page describing our info in detail: 
https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/POD+Aggregator+%28IvyPlus%29+data+set+and+mapping

I find the other fields to be problematic. AFAIK POD does not need them. Data provider requirements specificy that local bibliographic identifier be in a MARC 001 field so we don't want to suggest there are other options for that. As written it sounds like the field might be intended for local ITEM identifier, which is different, and I don't know why we'd want to define that here. Call numbers can span multiple subfields so I would not leave a field here for that. Same for local library. In short I think it's simplest if orgs can just include a link to where they define their data local data elements.

**Comment by ggeisler** [comment]
I think #564 and #565 cover the issues raised in the comment above, so they don't need to be addressed as part of this ticket.
