### ISSUE TITLE
Add "contact" field to New organization form

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#544]
The current new organization form at `/organizations/new` does not currently include a contact address field. However, through #515 and related discussions we decided to change "organization email contacts" to be an optional,  single-valued field. 

As a single-valued field representing a basic attribute of organization, I think it make sense to move this field from the current organization contacts location to a field editable through the "new organization" and "organization details" forms. This ticket focuses just on the new organization form accessed at `/organizations/new`

<img width="981" alt="Screen Shot 2022-04-04 at 3 44 47 PM" src="https://user-images.githubusercontent.com/101482/161645264-3039b469-6b0b-4143-bfba-1b91087ab495.png">

---

- [ ] Add a new "contact" attribute to organization and include it in the new organization form, just above the icon input, as shown above. Details:

Field label: `POD contact for this organization`
Hint: `An email address other POD users can use to contact this organization.`

**EDIT**: Note that the hint text above doesn't match the mockup exactly but that is the hint text we should use, rather than what you see in the mockup (update reflects the decision to only use email address for a contact.)

**Comment by corylown** [comment]
Do we really need to support a url pointing to a form or contact info or can we just use an email address?

**Comment by cbaksik** [comment]
We would like an email field. A separate URL field might be nice - to direct users the "right" part of the library website. 

We plan to use a single email that goes to a support team, and not to an individual person.

**Comment by JohnMarkOckerbloom** [comment]
I've sent out email to the pod-tech list asking whether anyone needs to use a contact URL for this, or whether a single email address is sufficient.  I'll see if I get any replies between now and Thursday's meeting, but at least for now I have not, and at least for Penn (per Bob) and for Harvard (per Corinna's comment above) a single email address would be fine.  I'll wait until after that meeting before making a definite decision, though.

**Comment by JohnMarkOckerbloom** [comment]
After a suitable interval, I have not heard from anyone needing a URL contact field.  So I think a single email address should be fine for now.

**Comment by JohnMarkOckerbloom** [comment]
I've answered the question above, but the implementation of the form addition needs to be done by someone else, so this issue should probably be reassigned to that person.

**Comment by corylown** [comment]
@JohnMarkOckerbloom I've unassigned you and queued this up for sprint 4

**Comment by corylown** [comment]
Relates to #545
