### ISSUE TITLE
Update the Manage/View organization Organization details tab/page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#546]
Related to https://github.com/pod4lib/aggregator/issues/534.

## Org admin version of the page

The next to last task in #534 suggest moving the first part of the form on the "Editing organization" page to be the main content below the tabs when the "Organization details" tab is active:

<img width="1197" alt="Screen Shot 2022-04-04 at 4 27 59 PM" src="https://user-images.githubusercontent.com/101482/161649280-3676e00f-ab41-4917-b521-a3ca492c5e7b.png">

---

Because we're splitting the current Editing organization form into two, on this page and the Provider details page, we can customize the label of the submit button on each page. Here:

- [x] Label the submit button `Update organization details`

We're adding "organization contact" as an optional, single-valued field, as described in #544 and #545. It therefore should be added to the form on this page, so an org admin can update their contact value.

- [ ] Use the updated (through #544) organization form on this page (or if it makes sense to maintain an independent form here, add the "POD contact for this organization" field as described in #544), so it ends up looking like the example above, with the red arrow (except the strings are Field label: `POD contact for this organization` and 
Hint: `How should other POD users contact this organization? Provide an email address or URL.`).

## Org member version of the page
We don't currently have a read-only view of this form for org members, but I think it would be useful for at least consistency purposes if the org member can see the values of this form, even if they can't update the form.

So, when the user is an **org member**, instead of displaying the editable form, we could show the current values in a description list:

<img width="1197" alt="Screen Shot 2022-04-04 at 4 38 24 PM" src="https://user-images.githubusercontent.com/101482/161649648-599952ce-959d-4cc6-90ea-f5047270ad73.png">

---

- [x] Omit the submit button in the org member's version of this page.

- [x] Put organization details form fields into a definition list. Use a `dl` element and put the value of each field label in a `dt` and the field value in a `dd`.

- [x] If for some reason it's troublesome to include the icon here, I don't think it's essential, since if it is defined the user should be able to see it in the top banner of the page.

- [ ] Indicate when a field has no current value. If for some reason there isn't a current value for any field, I suggest we display the string `no value provided` in italics so it's clear what the situation is:

<img width="1197" alt="Screen Shot 2022-04-04 at 4 31 22 PM" src="https://user-images.githubusercontent.com/101482/161649072-ee387ed0-03d1-4640-921b-f2df90563bab.png">

**Comment by cbaksik** [comment]
Definitely want a view only version of org page for org member. 

I haven't seen the term "slug" before and wonder if the Edit page should define a best practice and describe how that field would be used.

**Comment by ggeisler** [comment]
> I haven't seen the term "slug" before and wonder if the Edit page should define a best practice and describe how that field would be used.

On the one hand, the slug is first defined when the organization is created, which can only be done by a POD admin, and a POD admin likely knows what the slug is for. 

On the other hand, we make that field editable, so after the organization is created it can be changed by the organization admin, who might be less likely to know what it's for (although if so, probably also unlikely to feel a need to change it?). One option might be to add hint text below the input:

<img width="715" alt="Screen Shot 2022-04-07 at 4 13 28 PM" src="https://user-images.githubusercontent.com/101482/162334597-c472dfcb-3e0f-4e4e-9604-90c156a9a273.png">

Though this raises a couple of other questions:

- Is there a reason we want to make this attribute editable though the UI after the organization is created? Seems like changing an existing slug is an unlikely enough use case that maybe only a superuser should be able to do it, or maybe in those rare cases it could be done directly by a developer and not shown in the UI (other than the New Org form) at all?
- Could we just use the organization Name value to programmatically create the slug (lower-case the org name, snakecased if it is more than one word), thus leaving it out of the form entirely? Doesn't seem like we should need to worry about duplicate organization names in POD, and it isn't really exposed to end-users (other than the URL), so I'm wondering if we even need to give anyone control over what the slug actually is.
- (A less drastic variation of the above is to do what we do in Spotlight when creating a new exhibit: the Slug field is editable, but we populate it for the user using a snakecase version of the title they've given the exhibit, so they don't really need to think about it. See example below.)

<img width="643" alt="Screen Shot 2022-04-07 at 4 29 16 PM" src="https://user-images.githubusercontent.com/101482/162335713-5a6f5db8-5701-42f8-8cfd-8f64f18e14f3.png">

**Comment by cbaksik** [comment]
I like the idea of the POD Admin creating it. If the org is not happy with it, they can ask for it to be changed.

**Comment by corylown** [comment]
A few thoughts on this. I think we probably should remove the ability to edit this through the UI once after the org has been created. I can't see a good reason for changing the slug once it's created and if the need does arise a developer could make the change via the Rails console. Since the slug is created by a POD admin it seems like a low priority to make improvements, but I think option 3 that @ggeisler suggested above (editable, but with a pre-populated suggestion) is a nice approach.

**Comment by ggeisler** [comment]
Okay, I suggest we move forward on this by:

- Doing nothing different in this ticket (@marlo-longley ignore the discussion above about the slug for purposes of this ticket)
- I'll create a new ticket about updating how the slug field is handled, and indicate there that that change is lower-priority and shouldn't be tackled until the other couple of tickets related to the org details form are completed
