### ISSUE TITLE
Provider page > MARC analysis tab uppercase X, description change

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#561]
In the MARC analysis tab (currently called Profile as I write this), from #531 , use uppercase X. Uppercase is standard convention when referring to multiple MARC fields, as seen in [Library of Congress MARC documentation](https://www.loc.gov/marc/holdings/echdhome.html). 

Change "MHLD" to "Holdings data." MHLD is less universally recognized. 

Change "Multilingual" to "Multiscript." The 88X fields refer to the presence of [non-Latin scripts in records](https://www.loc.gov/marc/holdings/echdmulti.html) that have both transliteration and vernacular. 

In the Info column, the first line shows # of 001 fields. Please add commas to the numbers. 

(I might have more feedback but can only see what's in screenshot right now. Haven't seen whole page yet.)

**Comment by ggeisler** [comment]
@cbaksik It looks like you have a POD account so you should be able to get to the (pre-redesigned) page with links to the profile/analysis pages, in case you want to examine them more fully: https://pod.stanford.edu/organizations/harvard

The first magnifying glass icon in the files table is the analysis for the whole stream (takes quite a while to load, like maybe a full minute) and the others for the individual file they're associated with.

**Comment by cbaksik** [comment]
@ggeisler  Thanks, I didn't wait long enough and I thought maybe it wasn't working on prod yet. This is my new favorite page. The rest is great - no other feedback.
