### ISSUE TITLE
Add a field for providers to display a link to local MARC info

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#565]
Derived from a comment in #542. This would be applicable to the Manage/View organization page, the Provider details tab. There are other questions about the content on this page (see [comment in #542](https://github.com/pod4lib/aggregator/issues/542#issuecomment-1092197109)) so we might decide to [re-think what exactly we display on this page](#564), but this comment seems like something we can treat separately, as a new feature of the page:

> I would like a field to place a URL that will link to a local page describing our info in detail:
https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/POD+Aggregator+%28IvyPlus%29+data+set+and+mapping

**Comment by ggeisler** [comment]
Below is a suggestion for adding a MARC documentation field to the organization Provider details tab. There are two parts to update: the form for entering the link to the MARC documentation and the read-only version of the form that non-privileged (in this case, users other than POD admins and org owners for that organization) users see.

## Update the Provider details editable form
This form already has an `<h4>` element ("Item information") associated with the existing form fields. Below I'm suggesting we add the new elements before the existing ones.

<img width="811" alt="Screen Shot 2022-05-23 at 2 42 58 PM" src="https://user-images.githubusercontent.com/101482/169912677-7c220f99-abf7-4fd8-90f4-5c079e4b4a6e.png">

----

- [ ] **A:** Add a new `<h4>` element with the label `MARC documentation`
- [ ] **B:** Form label: `Local MARC profile documentation`
- [ ] **C:** New text input field. I think this might need to be optional (unless we know all POD organizations have provided a value) but if a value is entered in the field input, ideally we should [validate that it is a valid URL](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url). If it isn't, show the input error message `Please enter a valid, publicly accessible URL.` directly below the input field, before the hint text element, as shown below.
- [ ] **D:** Hint text for the field: `A public URL linking to MARC profile documentation for your organization`

---

<img width="811" alt="Screen Shot 2022-05-23 at 3 00 11 PM" src="https://user-images.githubusercontent.com/101482/169912712-f1fa5c66-7efd-461d-8cce-e7b31882601f.png">

---

## Update the Provider details read-only page
Use the existing `<dl>` structure to add a new `<dt>` and `<dd>` to the top of the existing list.

- [ ] `<dt>` value is: `Local MARC profile documentation`
- [ ] `<dd>` is the field input value provided, displayed in a link tag. If no value is provided, use the same "no value provided" fallback we use for other fields on this form.

<img width="811" alt="Screen Shot 2022-05-23 at 2 22 22 PM" src="https://user-images.githubusercontent.com/101482/169912739-ef30d25e-4c59-4219-8a83-c9ec7189d621.png">

**Comment by corylown** [comment]
Looks good to me
