### ISSUE TITLE
Story: design a way to generate inter-stream deltas to support harvesting

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#568]
- Also need to determine how to manage streams and default streams to support accurate calculation of inter-stream deltas.

**Comment by JohnMarkOckerbloom** [comment]
As noted in the meeting, at minimum this may require keeping a record of when different streams became the default (for at least as long as those streams are present in the system, and were default at some time within the interval for which we're supporting incremental harvests).  

With that, I believe we should have enough data to determine the content of the old and new default stream at the time  of a change in default stream, and therefore enough data to determine the differences between them at that time.  (There may be various ways of doing that efficiently.)  That should be sufficient to support incremental harvesting across time periods in which more than one stream acted as default for part of the period.

**Comment by corylown** [comment]
@JohnMarkOckerbloom I'm also thinking we might want to generate and save an md5 hash or something of each MARC record so we can determine if it has changed between streams.

**Comment by JohnMarkOckerbloom** [comment]
Good to know.  Does that give the time of the change in default streams as well as the order?  That, or something else that would enable us to determine what the contents of the streams were at the time of the change, would also be needed.

**Comment by JohnMarkOckerbloom** [comment]
That's useful!  Depending on how much work it is to analyze paper trails, it might be helpful to derive a concise summary representation of the stream changes that could be consulted by the delta generators and/or the OAI service.

**Comment by corylown** [comment]
@JohnMarkOckerbloom Some proposed work to move this along:

**Default Stream History**
-  Return a default stream history for each organization (use paper_trail model history tracking or other means). The list of current and former default streams, as well as date ranges when each stream was the default should be returned.
- On the streams index page and each stream's show page if the stream was ever the default display the label "Former Default Stream" along with the date ranges it was the default.

**Default Stream Management**
- Prevent organization owners from deleting streams that are or have been the default stream?
- Prevent organization owners from setting a stream that was previously set as the default to being the default again? (To maintain integrity of default stream order)
- When making a stream a default warn and require ackowledgement that making a stream default should only be done after the stream is complete (contains a full dump). Also warn that the currently default stream cannot be deleted and cannot be made the default again.
- Prevent uploading files to streams that were formerly the default?

**Inter-stream Jobs**
- GenerateInterStreamDeltaJob: Given a current or former default stream generate a list of MARC record 001 IDs that have NOT changed between the given stream and the prior default stream. Store this list in a file or db table associated with the given stream.
- GenerateInterStreamDeleteJob: Given a current or former stream generate a list of MARC record 001 IDs that are present in the previous default stream and absent in the given stream. Store this list in a file or db table associated with the given stream.

**Comment by thatbudakguy** [comment]
> Prevent uploading files to streams that were formerly the default?

I wonder if we could use the existing `Stream#archive` behavior for this, and just immediately archive a default stream when the default is changed to a new stream. That should (though it currently doesn't do all of these):
- prevent any further uploads to it
- prevent it from being made the default again
- schedule its uploads to be cleaned up after 6 months

I think archiving uploads gets rid of the underlying files, but we still have the records in the database, so in this scenario it's OK to archive former default streams since it's really just cleaning up their underlying files. We could then use the "archived" state (in addition to being noted as a former default) to protect against further uploads or usage.

**Comment by thatbudakguy** [comment]
> `GenerateInterStreamDeltaJob`: Given a current or former default stream generate a list of MARC record 001 IDs that have NOT changed between the given stream and the prior default stream.

does this refer to records that are the same item (MARC001 is the same), but the record metadata itself could have changed? or does that not matter?

**Comment by corylown** [comment]
@thatbudakguy I think we'd want to compare the records to check for changes.

**Comment by JohnMarkOckerbloom** [comment]
I don't think it's necessary to prevent a stream from becoming default a second time.  (It's not the usual workflow I'd imagine, but I can imagine a workflow that involves that.  For example, a provider might decide to do frequent, small-scale updates in one stream, and less frequent, larger-scale updates in the other.)  This doesn't seem to necessarily make inter-stream delta handling harder, as long as those deltas are linked to a change event, not to a stream in general.

**Comment by JohnMarkOckerbloom** [comment]
I do agree that preventing the deletion of streams that are or have recently been the default would be a good idea.  (Where "recently" refers to any time within the window we say we support incremental OAI updates, something on the order of 6 months.)

**Comment by cbaksik** [comment]
As a provider this doesn't entirely make sense to me. One of the reasons a provider may need to provide a new stream is that their deletes were all "messed up," e.g. something went wrong on the publishing side and deletes were not properly recorded, and the provider isn't sure what records in POD needs to be removed. In those cases the library does a full data dump and starts fresh in a new stream. 

If there is an "inter-stream" delta, would it know that a record absent in the new stream needs but present in the old stream, needs to be deleted entirely? 

Thanks!

**Comment by JohnMarkOckerbloom** [comment]
@Cbaksik: It would indeed be a requirement of a correct inter-stream delta that a record absent in the new default stream but present in the old stream would need to be noted as deleted in the delta.  So a provider should be able to "start fresh", if they saw fit, with a new full dump in a new stream, and it would be up to the POD Aggregator to generate a new inter-stream delta noting, among other things, what records in the old default stream were not present in the new default stream at the time of the default stream change.  That would enable an incrementally harvesting consumer to also see that they should delete those old records.

**Comment by corylown** [comment]
This issue is now tracked via several smaller issues:

- #599 
- #600 
- #601 
- #602 
- #603

**Comment by corylown** [comment]
Completed via #599, #600 & #602. We can let #603 stand on its own.
