### ISSUE TITLE
Enable org owners to promote org members to owners

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#578]
Related to #539 but I don't want to interfere with progress on that ticket so this could be handled after the work in #539 is merged.

A stakeholder mentioned that she thought org admins should be able to promote members of their organization to org admins (rather than this promotion having to be done by a superuser) and the consensus seemed to be this is a good idea. So this ticket is to update --  _in the case where the user viewing the page is an org admin of that organization or a superuser_ -- the "Role" column of the organization Users tab (assuming #539 is completed) to include checkboxes for indicating whether a given user is an org member or an org admin.

<img width="1149" alt="Screen Shot 2022-04-11 at 4 47 30 PM" src="https://user-images.githubusercontent.com/101482/162851035-6c238ab6-9a6b-4293-8a9f-e9ee077b5b7b.png">

---

When the user viewing the organization Users tab/page is an org admin of that organization or a superuser (otherwise we display the same read-only version of the page as described in #539):

- [x] **A:** Replace the "Role" table heading with `Organization admin?`
- [x] **A:** Replace the "Member" or "Admin" strings in the column with a toggle (or checkbox) that reflects that row's user role (on/checked means that user is currently an org admin)
- [ ] **B:** Add a `Update users` submit button to submit any change to the new "Organization admin?" toggle states

**Comment by corylown** [comment]
I think for now we should be consistent with the internal role names and refer to these roles as Org Owner and Org Member in the UI.

**Comment by JohnMarkOckerbloom** [comment]
I'm all for consistency.  I do have a slight preference for org admin[istrator], as a bit more accurately describing their role, but can go with either admin or owner, as long as we pick one.  What do others think concerning the terminology?

**Comment by thatbudakguy** [comment]
i agree that "org admin" more accurately describes the role. my understanding is we're going to change the names to what we agreed on whenever we decide to address things like #502, at which point "POD Admin" will also become "Superuser".

**Comment by ggeisler** [comment]
I prefer "Org admin" but am also fine with waiting to change it in the UI until the most appropriate time for managing the technical work.
