### ISSUE TITLE
Links at top of screen in Chrome

### ISSUE THREAD

**Issue by bobpersing** [pod4lib/aggregator#579]
The links in the black bar at the top of the POD screen are displaying correctly in Firefox.  In Chrome, though, they're not correctly spaced, and overlap each other.  Resizing the window doesn't make a difference.

![screenshot-pod stanford edu-chrome-2022 04 12-09_04_28](https://user-images.githubusercontent.com/74777933/162969239-89059cb3-f7a9-4411-a8ce-66e7337e7892.png)
![screenshot-pod stanford edu-firefox-2022 04 12-09_00_58](https://user-images.githubusercontent.com/74777933/162969242-7c96e80c-c750-43ca-81a2-7794eec973b3.png)

Screenshots attached.

**Comment by ktamaral** [comment]
Pull Request: https://github.com/pod4lib/aggregator/pull/582

**Comment by corylown** [comment]
@bobpersing thank you for reporting this. The fix is applied to the main branch of the project and will be deployed to production next Monday (at the latest) with dependency updates.
