### ISSUE TITLE
Update Site users page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#586]
There's currently a Site users page (`/site_users`) that I believe is only accessible to POD Admins. Below is a suggested redesign for this page.

<img width="1199" alt="Screen Shot 2022-04-12 at 11 45 11 AM" src="https://user-images.githubusercontent.com/101482/163032482-4b7a7100-ecef-4ddc-84ae-a8957e532b43.png">

---

- [x] **A:** The topbar navigation link "Users" should only be visible to superusers/POD Admins (this might already be the current behavior).
- [x] **B:** Rename the page heading to "Manage users" from its current "Site users"
- [x] The main updates in this issue are with this table, primarily adding/rearranging columns. Note that there is a related issue (#539 and #578) for the Organization users page, which includes a similar table. Since that work appears to be largely done, we might want to borrow the updated table code from that issue (not only to make development more efficient but to ensure the user seems a consistent pattern for managing users in both places). There are some differences in the two tables, though.
- [x] **C:** The current Site users table shows, in the first column, the user's name if it exists, otherwise the user's email address. I'm suggesting we break those into two distinct columns. Email address is required, so the first column always contains that. If the user provided a name, that goes in the second column, otherwise it is blank. The value in the first column can continue to be a mailto: link.
- [x] The current table shows, in the first column, the user's job title if it exists, in parenthesis. I suggest we drop that from this table (it is still visible in the Organization users page, where it might have more value).
- [x] **D:** Add a new column `Organization`. Link the organization value to the default tab/page of that organization's "Manage organization" page (see #539).
- [x] **E:** The current Site users table includes a final column that has buttons that either promote or demote a user from the POD admin role. This `Superuser?` column is intended to do the same thing, but using a checkbox/toggle instead of a button.
- [x] **F:** When we change the buttons to checkboxes in the Superuser? column, I think we might need to submit any changes to the checkbox, rather than that action taking place immediately. Assuming that's true, add a submit button with the label `Update users`.

**Comment by corylown** [comment]
For consistency with the internal role names, let's refer to the `admin` role as "POD Admin" in the UI (instead of of superuser).

**Comment by thatbudakguy** [comment]
@corylown does this mean we should also refer to the org admin role as "Org owner"?

**Comment by thatbudakguy** [comment]
nvm, saw your comment on #578

**Comment by thatbudakguy** [comment]
@ggeisler since there's no "remove user" button here, does that mean:
- the only place to get rid of a user account is on an organization's users page
- clicking the "remove user" button on the organization users page doesn't just remove the association between that user and the organization — it deletes the account entirely

**Comment by ggeisler** [comment]
@thatbudakguy 

> the only place to get rid of a user account is on an organization's users page

Yep. I originally had it on the site users page, but I'm not sure it's a good idea to offer the same feature in two places within the application. It likely just leads to someone getting confused over whether they are different somehow. And since a user **must** belong to one and only one organization, removing the user on the organization users page feels like the most direct place to do it; otherwise an org admin who is not a POD admin would have to ask a POD admin to remove the user from their organization.

> clicking the "remove user" button on the organization users page doesn't just remove the association between that user and the organization — it deletes the account entirely

Right, the user belongs to that organization and only that organization and the org admin has decided to remove that user, so they are removed from POD entirely. The only downside of that I see is if an existing POD user is switching organizations, but that seems like a rare enough case that removing them from POD and then inviting back to POD to their new organization is not unreasonable. (This wouldn't be as reasonable if we kept track of user-specific activity data or preferences, but we don't.)

But let me know if either of those answers doesn't make sense to you.
