### ISSUE TITLE
Restrict visibility of and access to the "Activity" topbar navigation item to POD admins

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#589]
As part of the on-going application reorganization, we've moved the uploads charts to the Providers index page from the Activity page, leaving the Activity page with just the "Uploads" table. The rationale behind this is that while general POD users might be interested in a high-level look at POD upload activity (via the charts now on the Providers page, or something similar we replace them with), the detailed "Uploads" table is likely not necessary for normal, everyday POD usage.

I'm going to create a separate issue to track the need to consider other information we might add to the Activity page, but I think at this point there's no reason to continue giving non-POD admins access to the Activity page, so:

- [ ] Restrict visibility of and access to the "Activity" topbar navigation item to superusers/POD admins

(Note that I am working on a redesign of the Uploads table on the Activity page, but that is [tracked in a separate issue](#477).)

**Comment by corylown** [comment]
To clarify: org owners and org members would not see this link
