### ISSUE TITLE
Update Activity page with additional info superusers care about?

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#590]
As part of the on-going application reorganization, we've moved the uploads charts to the Providers index page from the Activity page, leaving the Activity page with just the "Uploads" table. The rationale behind this is that while general POD users might be interested in a high-level look at POD uploads activity (via the charts now on the Providers page, or something similar we replace them with), the detailed "Uploads" table is likely not necessary for normal, everyday POD usage.

However, we've kept the Uploads table on the Activity page so superusers have access to it. I'm working on [improving the layout and organization of the "Uploads" table](#477) on that page, but am wondering:

- Is there other information about POD activity that might be useful to superusers/POD admins? We could potentially add some summary tables/charts back (perhaps some sort of statistics by provider) to the top of the Activity page if they would be helpful to superusers/POD admins, but I don't really know enough to suggest what these might be.

#196 lists some things that might fit in here?

**Comment by cbaksik** [comment]
I won't be an admin or superusers but if I were I'd want to know if there were any institutions that hadn't contributed in a while (maybe a month?), or who didn't have a successful load in the past month, as a way of getting ahead of a potential issue. (There isn't a guideline yet on how often everyone will contribute.) . Or instead, a little graphic of when each partner last sent in data and highlight any that are over a month of inactivity

**Comment by ggeisler** [comment]
Closing this as we have #672 as a more actionable place to manage the work on the Activity page.
