### ISSUE TITLE
As a developer I want to track the history of default streams for each organization

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#599]
In order to calculate accurate deltas between streams we need to track the history of an organization's default streams. This could be accomplished a number of ways:

- Reconstitute the default stream history from the model change tracking that is already taking place via the [paper_trail](https://github.com/paper-trail-gem/paper_trail/) gem.
- Add a model associated with the stream model for tracking when a stream was a default. For now, assume that a stream could be the default stream for more than one period of time.

At the very least we need to track the stream, the timestamp it became the default, and the timestamp it stopped being the default.

**Comment by Hurlyburly2** [comment]
Plan as of talking with @corylown this morning:
DefaultStreamHistory model
org (foreign key required) | stream (foreign key required) | order (not necessary, but nice to have. required if we have the field) | start_time (required) | end_time (nullable)

Create an entry any time the default field changes.

Before save callback -> check for change to the Stream's default property -> create a new DefaultStreamHistory. Also update previous (find where default is removed from previous stream) with end_time. 
For existing data - look through current streams and add a DefaultStreamHistory entry in the table (either a rake task to be run once, or account for possibility of no history in the code).

**Comment by Hurlyburly2** [comment]
https://github.com/pod4lib/aggregator/pull/617

**Comment by corylown** [comment]
Closed via #617
