### ISSUE TITLE
Reanalyze button takes user to confusingly similar page

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#607]
I just want to make sure this is intended. Steps:

1. From the default organization page (here /organizations/stanford), click "Reanalyze"
![Screen Shot 2022-04-14 at 14 12 20](https://user-images.githubusercontent.com/1328900/163477005-8822b0a8-a86a-42e7-a121-d1dd65da96b1.png)

2. You are routed to the stream's specific page at (/organizations/stanford/streams/thedefault) which looks like this:
![Screen Shot 2022-04-14 at 14 12 32](https://user-images.githubusercontent.com/1328900/163477308-f529ad26-f728-428b-afd0-6f6d27803d80.png)

The page is very similar, just without the tabs we are implementing for the Provider page. This confused me, I didn't know where I was in the app. Is this intended? Should the stream pages look different than the Provider Pages? Should they also implement the tabs? I am likely missing some context, thanks!

**Comment by ggeisler** [comment]
@marlo-longley This is not a technical answer but if I remember correctly, before you made the updates to the org page selecting "Re-analyze" performed an action without a noticeable change to the page. Perhaps it refreshed the page so it just looked like nothing changed, but I think the point is that action shouldn't redirect the user anywhere. At most it would refresh the current page.

We probably should consider a flash message to indicate the "Re-analyze" action was accepted and is underway (does this create a background job? If so, we could include a link the flash message to the Processing status page, Action jobs open), but that's beyond your question, I think.

**Comment by ggeisler** [comment]
Oh wait, I see now from your second screenshot we already do show a flash message. So at least from a UX point of view, ideally after the user selects "Re-analyze":

- Remain on current page (no redirect)
- Display the current flash message
- If applicable, add to the current flash message `View current processing status.` as a link that redirects to the processing status page

**Comment by marlo-longley** [comment]
@ggeisler thanks! That makes sense not to redirect the page, I'll try to implement that.

I guess this situation just revealed to me that stream pages like `/organizations/stanford/streams/thedefault` contain the same info and header as the Provider page `/organizations/stanford` which shows the default stream, but the /stream page shows everything in one vertical view without the tabs.

**Comment by corylown** [comment]
@marlo-longley yeah...that's not great. I think we can fix it by changing [this line](https://github.com/pod4lib/aggregator/blob/main/app/controllers/streams_controller.rb#L71) to something like:

```
format.html { redirect_back_or_to([@organization, @stream], notice: 'Upload was successfully updated.') }
```

**Comment by marlo-longley** [comment]
Per discussion in the permissions doc, I am going to restrict seeing the Reanalyze button to only POD admins and Org Owners.

**Comment by corylown** [comment]
@marlo-longley I think the re-analyze stream button should remain restricted to POD Admins. I've updated the spreadsheet to reflect this.
