### ISSUE TITLE
Harvard: File stuck in "Extract MARC record metadata job" 

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#611]
We have a file in our Active jobs list with status "Extract MARC record metadata job." The file is from Feb 22, 2022. We're not sure why it's stuck at that status. 

![image](https://user-images.githubusercontent.com/788203/163590398-fab1c68d-5ce6-4511-ae8b-8ec6addc33ba.png)

**Comment by cbaksik** [comment]
@Hurlyburly2 @ktamaral

**Comment by corylown** [comment]
I was able to find the upload this job was associated with and it appears to have successfully processed. This may be left over from before I re-analyzed all Harvard's uploads. I've deleted this job tracker.

**Comment by awoods** [comment]
@cbaksik / @corylown : This issue can now be closed, no?
