### ISSUE TITLE
Harvard: default stream - Normalized Data file list is empty

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#612]
There is no normalized data in our Normalized data file list. We'd expect to see a full file of the current data set. 

![image](https://user-images.githubusercontent.com/788203/163590676-4a0a2e36-2cad-44d6-9b4c-c1d203dcbf43.png)

**Comment by cbaksik** [comment]
@Hurlyburly2 @ktamaral

**Comment by corylown** [comment]
This is known issue, currently being addressed via: #583
