### ISSUE TITLE
As a User, I want an indication as to whether a previous stream was a default

### ISSUE THREAD

**Issue by Hurlyburly2** [pod4lib/aggregator#616]
Along with any other signalling around this issue (can it be deleted? etc)

Fill in more detail to this issue as we learn more.

**Comment by corylown** [comment]
@ggeisler we're going to start keeping track of streams that were formerly set as the default. We'd like to indicate this in the UI in the [list of streams](https://pod.stanford.edu/organizations/stanford/streams) and on the stream's [show page](https://pod.stanford.edu/organizations/stanford/streams/20220213) as well. We will also know the date range that the stream was the default and it might be helpful to display that information. It is possible that a stream could be set to the default for more than one period of time.

**Comment by ggeisler** [comment]
Closing this in favor of more actionable tickets #769 and #771.
