### ISSUE TITLE
Can we produce statically generated oai responses like we do for normalized MARC dumps?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#618]
This is @cbeer 's idea and I think it's worth considering:

- It would allow us to use processing jobs we already have in place to produce static oai response files. Performance should be good because we do the work in the background and just return a file on request.
- We'd be supporting "from date" requests in increments of 1 day since that's how frequently we produce deltas.
- To support "from date" requests that span multiple streams we could produce inter-stream delta files and return these instead of the full dump files.

Some issues to consider and questions:

- We would potentially be returning a large number of records in a single file (millions). This might be unexpected by some clients. But we're wondering if index data could handle this on an initial request for a full dump. Incremental deltas would be smaller.
- Is it a problem if we have a stream that has deltas but no full dumps? I think I've seen this scenario and it could make returning inter-stream deltas a problem because we wouldn't know that the first deltas were really full dumps.

**Comment by corylown** [comment]
@JohnMarkOckerbloom interested in your thoughts on this approach when you get a chance.

**Comment by JohnMarkOckerbloom** [comment]
This seems like a potentially useful way to go.  I've also used static files for handling some requests (including possibly some OAI requests) for The Online Books Page.  As I implement it, the files aren't literally the response, but the literal response either puts a wrapper around the files or does a trivial transformation on them in the output.  Either way, the response is quite fast.

One-day granularity is explicitly mentioned in the OAI spec as reasonable.  You can indicate in your response to the Identify verb that that's what you provide.

Index Data might or might not be able to handle millions of records in a single response.  (Even if they can, other potential consumers might have trouble with it.)  The usual "etiquette" I've seen in OAI-PMH providers is to break up large responses into chunks (where chunks typically range from 100-1000 records).  This is often handled server-side by first preparing the full response data (which would be what's in the static files in this scenario), and then returning the requisite number of records in the first response, along with a resumption token that, when included in a later request, essentially acts like a cursor telling the server where to start further responses.  This should hopefully not be too hard to implement as a transformation if need be.

**Comment by JohnMarkOckerbloom** [comment]
As I've noted in other tickets today, it sounds like Index Data needs to have responses in limited-size chunks (of no more than a few thousands records per chunk).  This is not necessarily incompatible with statically generated OAI responses, but those responses, if created, may need to span multiple files, and/or be dynamically generated from appropriate portions of the larger static response.

**Comment by corylown** [comment]
Closing this. This is the approach we're currently working toward.
