### ISSUE TITLE
Add info card to Normalized data section on Provider > Normalized data page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#621]
In response to @cbaksik's question in #613, we decided it would be helpful to add some information to the Normalized data section on the Provider page:

---

<img width="1037" alt="Screen Shot 2022-04-15 at 4 05 13 PM" src="https://user-images.githubusercontent.com/101482/163654161-800dafef-ebfc-4775-92cd-399717374122.png">

---

- [ ] **A:** I suggest we try using a Bootstrap card for this, full-width of the content area, using `bg-light` for the card header.
- [ ] **B**: For the icon, `info-circle-fill` (Bootstrap icon), using `bg-info` background color, maybe `18px` size (should be pretty small, ideally similar to the height of the heading font).
- [ ] **B:** Card heading is `About normalized data`, `1rem` font-size, `500` weight (bold like a heading, but otherwise style like body text).
- [ ] **C:** For the card body text: `Deltas and deletes are the changes since the full dump was generated. Full dumps are generated every 3 months. Deltas are generated daily. See the POD wiki for more details.` 
- [ ] **C:** The `See the POD wiki for more details.` part of the body text should be linked to the appropriate page/section in the wiki. However, there might not be an appropriate place, at least not yet, in which case we should omit it. @JohnMarkOckerbloom might have thoughts about this.

**Comment by JohnMarkOckerbloom** [comment]
I'm not quite sure what "full dumps are generated every 3 months" means in this context.  As far as I'm aware, full dumps are uploaded on the provider's schedule, not ours, though we recommend that it happen every 3 months or less, and that full dumps take place in new streams.  If this is instead a comment related to how and when normalized files are created based on file uploads, I wouldn't mind this being documented as part of issue #563.

**Comment by ggeisler** [comment]
@JohnMarkOckerbloom I based this text on an answer @corylown provided on the related #613. But obviously the text is very easy to change. So if you or @corylown can think of more helpful or accurate text to include in the box, feel free to add it in a comment. The main idea we're introducing here is the idea of an explanation callout for areas of the application where some definitions or explanations could be helpful to the user. But the text is certainly open for improving.

**Comment by corylown** [comment]
It's referring the scheduled production of _normalized_ full dumps and deltas.

**Comment by marlo-longley** [comment]
Blocked by https://github.com/pod4lib/aggregator/pull/620 (Normalized data page doesn't exist quite yet)

**Comment by corylown** [comment]
@ktamaral this should be unblocked now that #650 is complete.
