### ISSUE TITLE
How many records can IndexData handle in a single oai ListRecords request

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#631]
A normalized full dump could contain millions of records. We need to know how many records indexdata can handle in a single request/response to determine whether further work, such as #633 is needed.

**Comment by JohnMarkOckerbloom** [comment]
I can check with Index Data (probably on Friday's meeting) if they can consume feeds of that size in one gulp.  Longer term I think we need to be able to support chunking and buffering the response to better support clients who cannot easily do that, but if it's easier to implement the all-in-one-go version, Index Data can handle it, and responses of that size tend to transmit to completion without problems (another consideration), we can implement that first and add chunking and buffering later if that can't easily be done initially.

**Comment by JohnMarkOckerbloom** [comment]
Sebastian at Index Data indicated in today's meeting that, as far as he knows, their OAI handling client cannot handle super-large responses, but can handle chunked responses on the order of thousands of records.  (He can verify and/or get more specifics if necessary.)

This isn't necessarily incompatible with preparing a single-file response on our end, so long as there's also a way to parcel that response into smaller chunks with resumption tokens in the OAI-PMH replies.

**Comment by JohnMarkOckerbloom** [comment]
We've got confimation (thanks to @CoryLown) that Index Data does need chunked responses, and not the entire set at once.  It sounds like approximately 1000 records per response, give or take, would be a size that works well for them.

**Comment by corylown** [comment]
Closing this. Requirement to limit responses to 1000 records is noted in #711
