### ISSUE TITLE
Can we chunk large oai response files into smaller sets of records?

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#633]
If we determine that indexdata cannot handle large batches of records per request (#631 ) we may need to break up large oai response files into smaller chunks (and manage resumption tokens appropriately).

**Comment by JohnMarkOckerbloom** [comment]
Per the latest updates on #631, doing this will be necessary in the OAI-PMH responses for ListRecords.

**Comment by corylown** [comment]
Replaced by #711
