### ISSUE TITLE
Careful review of permissions in the application

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#634]
Review https://docs.google.com/spreadsheets/d/1_p8FkN_E_x5T_W1HF5bdX7m0eDt6xrLLMG8IIECBkcI/edit#gid=1891964460

And confirm behavior of the application conforms to our expectations.

**Comment by marlo-longley** [comment]
- [change from before] Org members should be able to view their own access tokens, but not the tokens of other orgs

**Comment by marlo-longley** [comment]
Closing -- we've reviewed permissions for current state of the app. Other things may come up which we will individually ticket.
