### ISSUE TITLE
Home "View organization" link for normal user should be updated

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#636]
When logged in as a normal user, the organization section of the homepage includes a "View organization" link. This link should go to the View organization page, to the default tab, which is Users. Instead it goes to the default organization page.

---

<img width="1010" alt="Screen Shot 2022-04-19 at 9 24 46 AM" src="https://user-images.githubusercontent.com/101482/164051486-976da57f-858c-43dc-818b-1c3c621ea4ad.png">

---

- [x] Link should go to `/organizations/[org]/users` rather than `/organizations/[org]`

**Comment by marlo-longley** [comment]
Closed by #655
