### ISSUE TITLE
Update user invitation mailer text

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#639]
This is not a high-priority (the current mailer works and is understandable) but I think we could make some minor improvements to the email that is sent when a user is invited to a POD organization.

- [ ] Subject line: `POD Aggregator invitation instructions` replaces current subject line string
- [ ] Remove link from the invitee's email address in the "Hello" line. 
- [ ] Update the paragraph that currently begins with "Someone has invited you..." to `You've been invited to join the [organization name] organization in the POD Aggregator (https://pod.stanford.edu). You can accept this invitation using the link below.` where [organization name] is replaced with the name of the org that invited the user (e.g. "Stanford"). Maintain the link for the POD url as it currently is.

If it is technically difficult to get the org name in this context, we could go with `You've been invited to join the POD Aggregator (https://pod.stanford.edu). You can accept this invitation using the link below.` instead (but including the org name would be nice because it helps legitimize the email, hopefully).

**Comment by ktamaral** [comment]
I've opened a PR for this. Note: Looks like it would take some additional work to add the organization name in this context, so skipping for now. Also it appears that the app is not adding a mail_to link to the email address, most likely the email client is adding the link to the email text.

For example this is the HTML of an invite email generated by the app, notice no mail_to link was created.

`Hello test7@example.com

You've been invited to join the POD Aggregator http://localhost:3000/. You can accept this invitation using the link below.

http://localhost:3000/users/invitation/accept?invitation_token=[REDACTED]


If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link above and set your password.`
