### ISSUE TITLE
Add an indication that the MARC analysis page is loading

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#658]
From the main provider page, when you select the "MARC analysis" tab, that page takes a while to load. But from a user perspective it isn't necessarily clear what is happening; a user could think the tab just isn't working.

We should add some sort of indication of the page loading situation.

**Comment by thatbudakguy** [comment]
I've noticed that this is often on the client/turbolinks side, and happens on other pages too. Interestingly, there is a default indicator (a small, thin line that crawls across the top of the screen), but it seems to be hidden by our current CSS. You can see it in the DOM while the page is loading (there's an invisible element whose width is rapidly being changed by javascript). Fixing this could be as simple as re-coloring/styling the line so it's visible to users (if we like that UX).

**Comment by ggeisler** [comment]
Ah yeah, I have noticed that progress updating in the web inspector but never connected it to the progress indicator at the top of the viewport. And I see that progress line at the top of the viewport in other Rails apps, such as Exhibits. 

So yeah, that would be an easy fix, although maybe not an ideal one, I'd argue, since I think it's easy to overlook. But I'd be okay with it as an interim solution, until and if we decide the MARC analysis page at least (since it is likely to almost always takes a fairly long time to load, and in a context where it's easy to think the tab you just clicked isn't working correctly or something) deserves something more prominent.

**Comment by thatbudakguy** [comment]
@ggeisler any thoughts on a color and/or thickness (in px) for this line, as an interim solution? i can make a quick PR

**Comment by ggeisler** [comment]
Let's try something pretty noticeable. Maybe the Bootstrap warning color (same as POD icon badge bg)? Maybe `3px`? Totally guessing, feel free to try whatever looks good to you.

**Comment by thatbudakguy** [comment]
cool, i'll try that. incidentally, just noticed that github has the same bar (maybe it's using turbolinks too) and they went with a blue color, pretty thin. visible (just) in this screenshot; nearly fully loaded:

![Screen Shot 2022-04-21 at 10 15 31](https://user-images.githubusercontent.com/4924494/164515148-5b103e1b-0cea-4180-8003-6b0ccca70c22.png)

**Comment by ggeisler** [comment]
Yeah, my suggestion for the warning yellow and a possibly thicker width line is the examples I've seen, like Github's, are very easy to not notice. Developers might notice them but I'm not sure they catch the attention of the average user. Especially with a color that is not a high contrast to the topbar (thus my suggestion for yellow to contrast with our dark topbar, rather than something like the blue Github used with their similar topbar color).
