### ISSUE TITLE
Organization header shouldn't change when moving between tabs on stream pages

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#659]
@marlo-longley might be aware of what's going on here but currently when you are on the main organization page and move between tabs ("Normalized data" or whatever) the organization header updates and the top-right link changes from "View/Manage organization" to "Default stream."

The "Default stream" link should only be displayed (I think) when you go to the Manage streams or "View/Manage organization" pages. Otherwise we should see the "View/Manage organization" link.

**Comment by corylown** [comment]
Closed via #663
