### ISSUE TITLE
Add new "Activity summary" section and tabs to Activity page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#673]
Part of #672.

The other tickets that are part of #672 focus on specific tables for the Activity summary section. This one is just about creating that section, setting up the tabs, and adjusting a couple of other things on the page.

<img width="979" alt="Screen Shot 2022-04-22 at 4 35 04 PM" src="https://user-images.githubusercontent.com/101482/164817541-331ec53a-8b23-472c-9630-ea58c9f4d58c.png">

---

- [x] Add a `visually-hidden` class to the current `<h1>` element on the page, with the "Recent activity" label (so it will be available to screenreaders but not displayed on the page).
- [x] **A:** Add a new `<h2>` element with the label `Activity summary`.
- [x] **B**: Add a new `<h2>` element with the label `Upload activity` just before the uploads table legend.
- [x] **C:** Set up a tab structure below the "Activity summary" heading to hold the different activity summary tables. These tabs should not be the pill-style tabs we used for the Organization pages. Use the [style matching the mockup](https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs).
- [x] We can tweak the labels and order as others see fit, but as a start:
- `Uploads`
- `Job status`
- `Normalized data`
- `Files`
- `Users`

**D:** The content for the tabs is described in the other tickets listed in #672.

**Comment by marlo-longley** [comment]
Though this was closed, I want to note that the PR did not include the Sparkline graph. That is broken out into a separate ticket #679
