### ISSUE TITLE
Add "Normalized data" table to Activity summary section

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#676]
Part of #672.

Below is a suggested start for the Normalized data tab. As with all of the Activity summary tables, the main goal is to start with something, and we can refine and adjust based on what data is actually feasible to gather and what ideas we might get for showing more useful things.

<img width="1145" alt="normalized-data" src="https://user-images.githubusercontent.com/101482/164841308-de883641-357d-47c3-95d4-25339ce00b93.png">

---

- [x] **A:** `Provider` column. Link to that provider's page > Normalized data tab.
- [x] **B:** `Last full dump` column. Date/time of the last full dump from that provider. If that provider doesn't have a full dump, display the `exclamation-triangle-fill` icon colored warning yellow.
- [x] **C:** `Dump records` column. Count of the number of records in the last full dump. Zero if they don't have a full dump. Right-align this column.
- [x] **D:** `Last delta` column. Date/time of the last delta file from that provider. If that provider doesn't have a delta file, display the `exclamation-triangle-fill` icon colored warning yellow.
- [x] **E:** `Last deletes` column. Date/time of the last deletes file from that provider. If that provider doesn't have a deletes file, display the `exclamation-triangle-fill` icon colored warning yellow.

**Comment by marlo-longley** [comment]
@ggeisler after digging into the data I realized that the dates for Last delta and Last deletes were the same when it comes to normalized data - because deletes are a type of delta. I just talked it over with @corylown and we thought removing column E here makes sense for now.
