### ISSUE TITLE
Johns Hopkins: problem uploading new file

### ISSUE THREAD

**Issue by bobpersing** [pod4lib/aggregator#683]
Jing Wang at Johns Hopkins uploaded several MARC files yesterday.  Most of them were successful, but one produced the error message below.  Does the trace below give any clue to the problem?

(Note: because of limitations in their Horizon ILS, they do all uploads from a Windows machine.)

c:\POD>curl --version
curl 7.82.0 (x86_64-pc-win32) libcurl/7.82.0 OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
Release-Date: 2022-03-05

c:\POD>curl -v -F 'upload[name]=JHUBD-220430-10.mrc;type=application/marc' -H "Authorization: Bearer ......" https://pod.stanford.edu/organizations/jhu/uploads?stream=JHUBD-2022-04-20
*   Trying 171.67.21.69:443...
* Connected to pod.stanford.edu (171.67.21.69) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: C:\curl-7.82.0-win64-mingw\bin\curl-ca-bundle.crt
*  CApath: none
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=Stanford; O=Stanford University; OU=IT Services; CN=pod.stanford.edu
*  start date: Sep 23 00:00:00 2021 GMT
*  expire date: Sep 23 23:59:59 2022 GMT
*  subjectAltName: host "pod.stanford.edu" matched cert's "pod.stanford.edu"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /organizations/jhu/uploads?stream=JHUBD-2022-04-20 HTTP/1.1
> Host: pod.stanford.edu
> User-Agent: curl/7.82.0
> Accept: */*
> Authorization: Bearer ......
> Content-Length: 200
> Content-Type: multipart/form-data; boundary=------------------------dde34de1731e54ff
>
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* We are completely uploaded and fine
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Date: Mon, 25 Apr 2022 14:14:34 GMT
< Server: Apache/2.4.6 ()
< X-Request-Id: a58a263b-ed52-4553-99ee-6bc0f547182e
< X-Runtime: 0.122304
< X-Powered-By: Phusion Passenger(R) 6.0.12
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Content-Length: 0
< Status: 400 Bad Request
< Connection: close
< Content-Type: text/html; charset=UTF-8
<
* Closing connection 0
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, close notify (256):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, close notify (256):

**Comment by corylown** [comment]
@bobpersing I think they may be using the wrong parameter to send the file. Looks like they're specifying the file and content type in the `upload[name]` parameter instead of the correct `upload[files][]` parameter.

**Comment by bobpersing** [comment]
From Jing:

I have tried both upload[files][] and upload[name] parameters.  It doesn't make a difference.

BTW, when clicking the "upload files" button, the following appears on the screen, which suggest both parameters shall work.
"You can also upload by submitting a POST with an http client (e.g. curl command). Note that you should only provide either upload[files][] OR upload[url].

  curl -F 'upload[name]=[NAME_OF_YOUR_FILE]' \
       -F 'upload[files][]=@[LOCATION_TO_YOUR_FILE];type=[THE_FILES_MIME_TYPE]' \
       -F 'upload[url]=[URL_TO_YOUR_FILE]' \
       -H 'Authorization: Bearer....."

**Comment by corylown** [comment]
Adding some context from email:

> Hi Bob,
Attached is the response from curl after I run the following script:
set "ORG_CODE=jhu"
set "STREAM_ID=JHUBD-2022-04-20"  
set "ACCESS_TOKEN=......"
 curl -v -F 'upload[files][]=@c:\POD\JHUBD-220430-11.mrc;type=application/marc' -H "Authorization: Bearer %ACCESS_TOKEN%" https://pod.stanford.edu/organizations/%ORG_CODE%/uploads?stream=%STREAM_ID% 2> upload.log3.txt
I am using curl version 7.82  on Windows 10 VM.
Thanks,
Jing

My response after digging through the logs:

> The 400 Bad Request response led me to think the curl request is malformed and I’m wondering if there’s some Windows-specific terminal/character issues at play. I grep-ed the logs and found that the parameters for Jing’s curl requests are being interpreted by the POD server as including single quote characters, like:
>  
> {"'upload"=>
>  
> And
>  
> @content_type="application/marc'"
>  
> And
>  
> name=\"'upload[files][]\"
>  
> The server won’t be able to correctly handle these requests because the parameters are wrong.
>  
> This is seeming like a Windows-specific terminal/curl issue. Maybe Jing could try double quotes instead of single quotes? Try without quotes?
>  
> If Jing is really stuck maybe a 30 min zoom session later this week would help? Then I could see what Jing is doing, suggest different things to try, and watch the production logs in real time.
>  
> Cory

**Comment by corylown** [comment]
My investigation confirms that curl on Windows parses command syntax differently than curl on Linux. Use double quotes for curl commands on Windows. Single quotes get included as part of the parameters, which is no good.

This should work:

```
 curl -v -F "upload[files][]=@c:\POD\JHUBD-220430-11.mrc;type=application/marc" -H "Authorization: Bearer %ACCESS_TOKEN%" https://pod.stanford.edu/organizations/%ORG_CODE%/uploads?stream=%STREAM_ID%
```

**Comment by corylown** [comment]
Resolved. JHU has been able to submit data.
