### ISSUE TITLE
Dartmouth: Empty streams created by aggregator, marked as Default

### ISSUE THREAD

**Issue by EJBivona** [pod4lib/aggregator#691]
Dartmouth currently has 60 streams in the aggregator, but only four of them were created by my code for uploading our contributions.  Additionally, one of the streams created by the aggregator is marked as the Default stream, even though I believe my code always marks our current upload stream as the Default.  Given that IndexData will be pulling from the Default stream, this is a problem.

I'm attaching two screen shots, one of the top of the streams page that includes the bogus Default stream, and one of the bottom of the page with the four real streams, including the current expected default "202204".  All 56 other streams are empty.

-Eric
-----
<img width="1224" alt="Screen Shot 2022-04-25 at 15 55 28" src="https://user-images.githubusercontent.com/3787120/165166015-05c42c23-f2cf-400b-94ca-b5e341efe170.png">
<img width="1224" alt="Screen Shot 2022-04-25 at 15 56 11" src="https://user-images.githubusercontent.com/3787120/165166046-da30a9d8-595b-4a7f-af9e-cd12d7d59d29.png">

**Comment by corylown** [comment]
@EJBivona is it possible you could share your script with me? I'm not seeing this issue anywhere else and I'm not sure how to duplicate the issue without seeing what your script does.

**Comment by corylown** [comment]
@EJBivona I did find some maybe unexpected behavior, detailed in #693, that I suspect may be in play with this issue. If your script is issuing a request to make the already default stream the default again, POD is toggling the default flag to false. Then, when you go to send stuff to the default stream there is no existing default so it creates a new one. It will take further analysis to determine if this is a bug or behavior that needs clearer documentation.

**Comment by EJBivona** [comment]
@corylown Yes, I believe my script is setting the stream I'm using to be the Default each time, because I saw early on the other streams being created.  I'll check later this morning.

It seems to me that setting the current Default stream to be the Default stream should be a no-op.  Anything else seems broken to me…

**Comment by EJBivona** [comment]
@corylown I have verified that my code sends an API Post to '/streams/make_default' with our current stream, e.g. '202204', after each upload.  If nothing else, my intent is to correct any confusion an admin user might have if they mistakenly change the default, given that the code that does the upload is trying to maintain a reasonable consistency in our contributions.

**Comment by EJBivona** [comment]
@corylown Any idea when the fix for #693 will be put in to production?  I saw that your change was merged into the main branch, but it doesn't appear to have been deployed, at least not as of 00:15 EDT.

**Comment by corylown** [comment]
@EJBivona the change was merged and deployed yesterday (although typically we deploy changes to production on Mondays).

**Comment by EJBivona** [comment]
@corylown Huh, I wonder why then, when I looked at Dartmouth's stream this morning, the default wasn't correct.

I could probably force the make_default API call and verify that the right thing happens, instead of waiting for things to run again overnight.

**Comment by corylown** [comment]
@EJBivona let me know what you find. The guard clause I added should fix the issue: https://github.com/pod4lib/aggregator/blob/main/app/models/stream.rb#L37

**Comment by EJBivona** [comment]
Okay, I just tried it a number of times, and the Default stream didn't change.  I'll take a look at it tomorrow just to make sure (maybe my upload and defaulting happened before the deploy, if it happens off-hours).

**Comment by EJBivona** [comment]
Our upload ran fine overnight, and the correct stream was still the Default this morning.  Thanks for the quick work on this!
