### ISSUE TITLE
There's no link back to organization home/default stream when viewing streams

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#692]
The organization name is no longer linked and there's no link to the right to get me back where I came from:

https://pod.stanford.edu/organizations/penn/streams

<img width="1416" alt="Screen Shot 2022-04-25 at 4 50 48 PM" src="https://user-images.githubusercontent.com/458247/165172787-3fee8842-6ecf-4803-8cad-eb05f8d57d42.png">

I would expect to find a link back to: https://pod.stanford.edu/organizations/penn

**Comment by corylown** [comment]
@marlo-longley thanks for the context. I guess that means we ought to put a link on the right side like we do in other contexts?

**Comment by marlo-longley** [comment]
seems right - can use the `<% content_for :org_header_section_link do %>` thing we put in place last week.

**Comment by marlo-longley** [comment]
@corylown have this working but there are some questions about the logic?
When you click into the default stream, what shouuld the link be? Below screenshot seems redundant?
This is where this difference between these two types of pages gets a little confusing. The link to "Default stream" links to the Provider org main page (the one with the tabs) not the Stream page. I wonder if changing the link title from "Default stream" to "Provider home" could be clarifying and avoid the confusion.

![Screen Shot 2022-04-25 at 15 29 55](https://user-images.githubusercontent.com/1328900/165185441-e654e1a3-7717-41c0-be0a-dbe3520ec1f7.png)
![Screen Shot 2022-04-25 at 15 30 02](https://user-images.githubusercontent.com/1328900/165185445-9de677b8-9564-4add-a337-c0daa52061ff.png)
![Screen Shot 2022-04-25 at 15 30 09](https://user-images.githubusercontent.com/1328900/165185446-abfea118-a98a-46e9-8705-e57c46d67c92.png)

**Comment by ggeisler** [comment]
The page in question (in the original ticket comment) is the Manage streams page, which I mentioned last week I plan to redesign (also noted in #616), which I haven't had time to do yet.
