### ISSUE TITLE
Dartmouth - making a user an owner creates a duplicate user

### ISSUE THREAD

**Issue by joemontibello** [pod4lib/aggregator#699]
As the designated "owner" of our organization, I went into the users page (https://pod.stanford.edu/organizations/dartmouth/users) to designate another user. After designating Eric Bivona as an owner, I noticed that the list of users now shows Eric twice and me twice. For each of us, we have one line that indicates being an owner, and another line indicating not being an owner:
<img width="1154" alt="duplicateusers" src="https://user-images.githubusercontent.com/1447749/165343011-ff285a8c-07c2-432b-b545-14e72ad9b84e.png">

This doesn't look right to me - it seems like giving the "owner" status to a user should just update the existing line for them on the list of users.

Take care,
Joe Montibello
joseph.montibello@dartmouth.edu

**Comment by corylown** [comment]
Closed via #700
