### ISSUE TITLE
Add "Provider home" link in organization header for uploads/index uploads/new and uploads/info

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#704]
Related to #692

**Comment by marlo-longley** [comment]
@corylown I'm not experienced with these parts of the app, as far as I can tell uploads/index looks like this?

![Screen Shot 2022-04-27 at 12 14 42](https://user-images.githubusercontent.com/1328900/165602355-637b7e5b-be6f-4eac-8ce7-0618d4bac95f.png) - the /edit link on this page doesn't work

**Comment by corylown** [comment]
Yeah, something is not right. But I think it's OK to ignore the non-functional Edit button for this issue.

**Comment by marlo-longley** [comment]
I can open a ticket. Just checking since I've never been to this page. Thanks.
