### ISSUE TITLE
OAI: respond to ListRecords requests 1000 records at a time

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#711]
- Respond in chunks (~1000 records at a time, with resumption tokens)
- Chunks could be filtered portions of pre-generated file, or a series of pre-generated files in a folder/directory

**Comment by thatbudakguy** [comment]
do we support `ListRecords` requests that don't specify a set (i.e. target all records in the aggregator)?

**Comment by thatbudakguy** [comment]
just saw john's comment on #569:
> We're aiming to have one set per provider organization (not per stream). OAI clients can request harvesting in full or with time-bounds from any of those sets. They can also make a request that doesn't specify a set.

so, `ListRecords` with no set should be supported.

**Comment by JohnMarkOckerbloom** [comment]
Just a note on this ticket: While I do think we need to support set-less ListRecords requests, I'm not aware of Index Data needing them, so it's higher priority to get institutional-set ListRecords requests working than setless ones.
