### ISSUE TITLE
Only allow POD Admins to destroy/remove an organization.

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#719]
Relates to #634 , conflicts with spreadsheet which specifies that only POD Admin should have destroy option.
Noted in spreadsheet

![Screen Shot 2022-04-27 at 15 45 18](https://user-images.githubusercontent.com/1328900/165643569-70b7b6a4-d2c3-43b5-a1cb-531beb604702.png)

**Comment by ggeisler** [comment]
I vote for this being a POD admin only power.

I think these buttons are just remnants of the original table when we didn't have the extra layer of privileges. I would also suggest we remove Edit from this table, even though the Org owner does have edit privileges. I think it creates confusion to have the same action appear in too many places, and the org owner can easily edit their organization via their org-specific homepage links or by simply selecting their provider name from the list in that table.

**Comment by corylown** [comment]
I agree that only POD Admins should be able to destroy an organization.

**Comment by marlo-longley** [comment]
Closed by #748
