### ISSUE TITLE
Dartmouth: can empty, obsolete streams be deleted?

### ISSUE THREAD

**Issue by EJBivona** [pod4lib/aggregator#727]
Dartmouth's stream page, <https://pod.stanford.edu/organizations/dartmouth/streams> includes many empty streams mistakenly created by the aggregator due to a bug in the /make_default API.

Out of the 61 streams listed, only 4 are valid, and have data.  I don't see any UI controls that indicate I can delete the spurious streams, nor documentation that indicates I can use the API to delete existing streams.

If I can't delete them, can they be cleaned up, or do we have wait for them to age out?

**Comment by corylown** [comment]
@EJBivona I've removed Dartmouth's empty streams. At the moment, only POD admins can delete streams.
