### ISSUE TITLE
Org owners and members can view all streams for all orgs

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#729]
Relates to #634

The permissions doc specifies that org owners and members should only be able to "view all streams" for their own organization.
Put another way, according to the document, org owners and members:
- SHOULD be able to view the default stream of all organizations
- SHOULD NOT be able to view non-default streams of non-member organizations

Currently however, org owners and members can view default and non-default streams for all organizations.

**Comment by JohnMarkOckerbloom** [comment]
Similar to what I said in #731, I don't see a major problem with allowing logged-in users generally to see all existing streams, whether default or not. The data we're sharing is generally considered "open" to other participants in POD, members know from the Framework that they're not supposed to misuse it, and there might be reasons for a member in one of the organizations to reach out to a member in another organization to ask or help answer a question about files in streams that are not currently default.

Does anyone else have reasons not to keep this permission open in the aggregator, and to update the permissions spreadsheet accordingly?

**Comment by corylown** [comment]
It also seems OK to me to let any logged in member or owner see other organizations streams.

**Comment by marlo-longley** [comment]
Thanks for the input. Spreadsheet is now updated and I'm closing the issue.
