### ISSUE TITLE
Org owners and members can view processing status of non-member orgs

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#731]
Relates to #634 

The permissions doc specifies that org owners and members should only be able to "view stream processing status" for their own organization. 

Currently however, org owners and members can view the Processing status tab on the Provider home for any (non-member) organization. Also, when viewing a stream page for any stream from a non-member org, the processing status accordions are viewable.

(screenshots show owner @ Stanford viewing Harvard; same applies for member @ Stanford viewing Harvard)

![Screen Shot 2022-04-28 at 11 56 55](https://user-images.githubusercontent.com/1328900/165826343-14371025-31b0-41f9-8161-b7a34ac6e535.png)
![Screen Shot 2022-04-28 at 11 57 03](https://user-images.githubusercontent.com/1328900/165826347-512f519a-a78a-4ab2-a871-457d2538b29c.png)

**Comment by marlo-longley** [comment]
context : https://github.com/pod4lib/aggregator/pull/649

**Comment by JohnMarkOckerbloom** [comment]
My comment here is similar to the one I made for #736: I don't see a major problem with allowing this for logged-in users generally. There doesn't seem to be anything particularly sensitive her. We're generally assuming at this point that participating organizations have a collegial relationship, and there might be reasons for a member in one of the organizations to look at the processing status in another organization to help troubleshoot (in this case, for something like answering a question like "can you tell from looking at this why these uploaded files aren't processing like I'm expecting?") 

Does anyone else have reasons not to keep this permission open in the aggregator, and to update the permissions spreadsheet accordingly?

**Comment by corylown** [comment]
Agree that I think it's fine to show processing status to members or owners of other organizations.

**Comment by marlo-longley** [comment]
Thanks for the input. Spreadsheet is updated and I'm closing the issue.
