### ISSUE TITLE
Source button on stream file info/profile page refreshes page

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#732]
Is this the intended behavior of this button?
Page in question can be found at URLs like : `/organizations/2/uploads/4/info/9`
Users can navigate to this page via the magnifying glass icon in the files tables.
![Screen Shot 2022-04-28 at 13 21 15](https://user-images.githubusercontent.com/1328900/165838953-876b46ea-fe42-42b3-b886-43d7d2457f09.png)

**Comment by JohnMarkOckerbloom** [comment]
Is this still a live issue?  I'm having a hard time finding an example of this button and its behavior.  What would be a complete URL I could try to see it?  (And/or, can anyone tell me what "Source" is intended to mean in this context?)

**Comment by corylown** [comment]
@marlo-longley @JohnMarkOckerbloom I think Marlo is referring to pages like this one: https://pod.stanford.edu/organizations/dartmouth/uploads/34142/info/38869

But I can't duplicate the described behavior. When I click on the "Source" button the browser downloads the linked file, which is the intended outcome. @marlo-longley are you still seeing the page refresh behavior your described?

**Comment by corylown** [comment]
@JohnMarkOckerbloom good find. I think what should happen is that either the source or the download link should appear -- not both. The download link should appear for uploaded files while the source link should appear for data submitted via URL. I'll open a new issue.

**Comment by marlo-longley** [comment]
@corylown is this closeable via https://github.com/pod4lib/aggregator/issues/784 ?

**Comment by corylown** [comment]
@marlo-longley yes, I'll close it.
