### ISSUE TITLE
Org owners and members can view users of non-member orgs

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#736]
Relates to https://github.com/pod4lib/aggregator/issues/634

The permissions doc specifies that org owners and members should only be able to "view organization users" for their own organization.

Currently however, org owners and members can view non-member org's users via the Users tab in View Organization details. Tests currently exist to validate this behavior, though it conflicts with the spreadsheet.

![Screen Shot 2022-04-28 at 14 13 55](https://user-images.githubusercontent.com/1328900/165846925-1a268402-11b3-4615-a0d7-fe24a4c568a6.png)

**Comment by JohnMarkOckerbloom** [comment]
I don't see a major problem with allowing this for logged-in users generally.  There doesn't seem to be anything in here more sensitive than a work email address, and that's not available on the open web to spam-harvesters. We're generally assuming at this point that participating organizations have a collegial relationship, and there might be reasons for a member in one of the organizations to reach out to a member in another organization for a question.

Does anyone else have reasons not to keep this permission open in the aggregator, and to update the permissions spreadsheet accordingly?

**Comment by corylown** [comment]
I agree that I don't think it's a problem (and could possibly be useful) to allow members and owners to see users of other organizations in POD.

**Comment by marlo-longley** [comment]
Thanks for the input. Spreadsheet is now updated and I'm closing the issue.
