### ISSUE TITLE
Update content and layout of Uploads index page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#745]
Related to #746.

The current [Uploads index page](https://pod.stanford.edu/organizations/stanford/uploads/) was just a very basic MVP implementation, I believe, and doesn't fit in well with the current application design. As an example, here's the current version:

<img width="967" alt="Screen Shot 2022-04-29 at 1 05 02 PM" src="https://user-images.githubusercontent.com/101482/166061944-507f45dd-509e-454e-9481-50c7e0d95a25.png">

---

Here's a suggested revision:

<img width="1076" alt="Screen Shot 2022-04-29 at 12 53 07 PM" src="https://user-images.githubusercontent.com/101482/166061611-51d069c4-271d-4eed-899c-0eb7e121953c.png">

---

- [x] **A:** Change the current heading "Uploads" to an `<h2>` (it is currently an `<h1`>).
- [x] **B:** Add a `New upload` primary button to replace the "New Upload" link currently at the very bottom of the uploads list. (Note that I'm suggesting `New upload` for the button label, which doesn't match the mockup; I changed my mind and forgot to update the mockup.)

Update the current table as described below:
- [x] **C:** Name column. Link the name of the upload. This is the link currently used as the "Show" link in the last column of the current table.
- [x] **D:** Add a date column.
- [x] Remove the Files column. The user can see the individual files that are part of an upload on the upload show page.
- [x] **E:** Add a `Stream` column. This isn't in the current table but I assume we know which stream an upload was created in? If so, add the column, displaying the stream name and linking that to the stream page. 
- [x] **F:** Add a column for `Actions` but only display this column to org owners and POD admins (that's my suggestion but permissions for these actions are not yet defined in the spreadsheet).
- [x] _Show_ action: Since the upload name will be linked to its show page, I don't think we should also display the "Show" action that is currently displayed. Remove it from this column.
- [x] **G:** _Edit_ action: Display this as a secondary button, **if** we can verify that this is an actual action that users might need to use. Currently selecting that action for an upload returns an error page.
- [x] **H:** _Delete_ action: If this is something we want a user to be able to do, make this a danger button.
- [x] Sort the table by Date (most recent first). I'm not sure how the current list is sorted but given the upload names are not easy to scan, I think finding an upload by date is likely the best way to organize the rows.
- [x] Use the `table-striped` class as on other tables.
- [ ] We probably should add pagination to this page, similar to how we added it to the Uploaded files table.

**Comment by marlo-longley** [comment]
A few questions: @ggeisler @corylown 
- Should section D be created_at or updated_at? Depending on the answer, maybe the column name should reflect that rather than just the general "Date"?
- Relatedly, since you're suggesting to sort by date, I'm assuming this would be the updated_at date?
- See #774 for issue with Edit button

**Comment by ggeisler** [comment]
@marlo-longley Yes, the answer to #774 should tell us whether to use `Created at` (no edit of uploads) or `Updated at` (we fix the routing so you can edit an upload).

Either way, that is the column we should sort by.

**Comment by corylown** [comment]
@marlo-longley good question about ability to delete an upload. It appears that currently POD Admins and Org Owners are allowed to delete uploads. I could imagine a scenarios where this is useful: you've uploaded something by mistake or there's some other problem with it. I also think it could be problematic to remove uploads in case the data has already been harvested by a data consumer. **I think for now I would leave the current abilities in place: POD admins and org owners can delete uploads.** We might need to revisit this when we look more closely at how to maintain data integrity for data consumers.

**Comment by marlo-longley** [comment]
Updates:
- Edit button is removed from this layout.
- Pagination is broken out into different ticket; I had errors and don't want to hold this back
