### ISSUE TITLE
Convert files legend into an info box

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#763]
This is a currently just a proposal. It's not ready for implementation until we remove the Question label. I'd like at least @corylown and @JohnMarkOckerbloom to weigh in on whether this seems useful, though feedback from anyone is welcome.

### Problem
We currently show a legend that is intended to help the user understand what the icons we use for file status mean. We display this legend immediately before the table of files on the Upload files page for a stream, and the table of files on the Activity page:

<img width="1163" alt="Screen Shot 2022-05-03 at 4 13 06 PM" src="https://user-images.githubusercontent.com/101482/166588324-744fa5b4-9156-4e59-a5ee-458c3deced61.png">

---

Because some of the status explanations are sort of long, it's not a very attractive legend, it wraps at viewports smaller than `XL`, and the longer entries make quickly scanning the list a bit harder. I'm also wondering, since we recently added some wording to a couple of the entries to be more clear, if we might want to be even more clear about the details of some of the possible file statuses.

At the same time, I suspect that any user of the POD UI who looks at the files table on a regular basis internalizes the icon meanings after a while, and then for that user the unattractive legend is just a distraction.

### Proposed solution
We might be able to do the following by converting the legend into an info box (Bootstrap card):

- Provide more space for longer explanations, in case we think it would be useful to be more descriptive for any status
- Hide the legend from the knowledgeable user (I suggest the box is expandable/collapsible, and collapsed by default), reducing the visual distraction

#### Example of default collapsed state
I think we'd want to display the box collapsed by default, since it seems reasonable to expect that a returning user might not need to see the legend very often. If they do it's just one click to expand.

I'd also suggest we make the whole card header the trigger for the expand/collapse action, since the icon can be pretty distant from the card heading text on wider viewports and thus less noticeable. (I don't love `About file status` as the heading text but we can work on that.)

<img width="1196" alt="Screen Shot 2022-05-03 at 3 53 38 PM" src="https://user-images.githubusercontent.com/101482/166587698-dee97b81-3ea6-4707-a789-a4a6162a227a.png">

---

#### Example of open state
Because the user is intentionally expanding the box, I worry less about the vertical space it takes. So I've used a new line for each file status. In my mockup this arrangement results in a lot of wasted horizontal space but I think we can consider writing expanded explanations for any status that might need it, which would use more of that horizontal space. Or, if we don't have useful expanded explanations, we could try to use a two-column layout within the box.

<img width="1196" alt="Screen Shot 2022-05-03 at 3 54 21 PM" src="https://user-images.githubusercontent.com/101482/166588313-446ff2ad-8f37-4be0-934f-59017549c1aa.png">

**Comment by corylown** [comment]
@ggeisler I like this proposal to move the status icon details into a collapsed but expandable info box.

**Comment by JohnMarkOckerbloom** [comment]
Does the collapsed info box take up substantially more vertical space than the existing horizontal-row legend, though?  (As Gary points out, it does when the window's narrow enough and the line wraps, but even on my 13" laptop that doesn't happen until I make my browser window smaller than usual; and I suspect that most people using this interface would be using a laptop or monitor-equipped computer rather than a mobile device or something else with a small browser window.)

Because this is most likely to be needed by new users, who also might not notice things they have to make extra clicks to see, I do have a slight preference for showing brief labels by default on one line if it fits.  (I've seen some interfaces that will have an element fully displayed at wide widths and then auto-collapse it into an expandable element at narrow widths, but I don't know how easy that would be to do cleanly here.) But it's not an especially strong preference, so I'm willing to yield to UX expertise judging otherwise.  Note that we can also potentially include a link to more detailed explanations in the documentation wiki if that seems appropriate.

**Comment by ggeisler** [comment]
The collapsed info box would require about the same vertical space as the current legend. The advantages of it over the legend in that regard are 1) it wouldn't wrap on narrower viewports, and 2) it would be less visually distracting for the user who already understands the file status info.

However, I do think @JohnMarkOckerbloom has a good point about most users of POD likely to be using a wide-enough viewport to not see the current legend wrapping. With the ubiquity of mobile devices today, it's generally good practice to **not** assume users won't be using a mobile device, but the user base of POD is somewhat unique and I agree we can be pretty confident most of the time they won't have a narrow viewport.

I think the deciding factor on which way to go might be: given the extra space the info box approach offers, would you take advantage of this by providing more detailed text for one or more status states? If you can't think of additional text about file statuses you think would be helpful for the user in the info box, it probably isn't worth the effort to implement the box. I might just remove the bolding from the legend text to reduce its visual impact a bit. It'll still be kind of ugly, but maybe that would be sufficient (again, though, that is assuming there is no additional text we could add to help the user better understand the different possible file statuses).

**Comment by corylown** [comment]
I think it's possible we would want to provide more detailed explanations for each status if we had the space in an info box to do so. That would likely be based on further feedback from POD users. One approach would be to for now remove the bolding from the legend to reduce its visual impact and if we find that more detailed information is needed we move to the info box approach.

**Comment by ggeisler** [comment]
Sure, that sounds fine to me. I'll take care of the bolding issue when I make another pass at some visual design tweaks.
