### ISSUE TITLE
Update Streams index page

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#769]
(This issue is closely related to https://github.com/pod4lib/aggregator/issues/771 in that whichever option (expand/collapse hidden date range info or use a tooltip to display it) we decide to go with, we probably should use that option for both that issue and this one.)

My understanding is we need to convey these new things to the user about default or previously default streams:

- Whether a stream was previously the default stream
- If it was previously the default, the date range, or date ranges, it was the default stream
- That they cannot make a previously default stream the default stream again

Below are two sets of mockups represented two different approaches to conveying this new information. In both approaches we would:

- Rearrange the first two columns of the current table so that `Status` is the second column (it doesn't currently have a heading, and is the first column)
- Add an `Actions` column heading for the last column that displays the "Make default" and "Destroy" buttons (if the user has permissions to those)
- Swap order of the the "Make default" and "Destroy" buttons 
- Change the label of the "Destroy" button to "Delete"
- When a stream was previously the default stream, add `Previous default` to its Status column

The difference between the two options below is how we enable the user to see the date range(s) a stream was previously the default:

- Using a disclosure icon to reveal table rows showing the date range(s) a stream was previously the default
- Using a tooltip to display the date range(s) a stream was previously the default

Overall, I think the tooltip option is simpler, UX-wise, but that option does mean adding some new Javascript and might be a bit harder to implement in an accessible way. Choosing between the two options is a technical decision as much as a UX one.

## Option A: Using a disclosure icon
With this option we would include the date range values for each stream that was previously the default stream as additional lines/rows in the table, but hide them by default:

<img width="974" alt="expand-none" src="https://user-images.githubusercontent.com/101482/166835508-ccad5c06-e350-4cfb-95f8-ef6e713ebb0f.png">

---

A user interested in knowing when exactly this stream was previously the default stream can use the disclosure icon to expand the hidden row to see the date range:

<img width="974" alt="expand-one" src="https://user-images.githubusercontent.com/101482/166835611-660f682b-e260-4903-99cc-352ad5c7f234.png">

---

If the stream was previously the default more than once (though I'm confused about whether this is actually possible, since one of the requirements I heard was not allowing a stream that was previously the default to be made the default again; but maybe it used to be possible so we have to account for that?), we'd just display additional lines/rows:

<img width="974" alt="expand-two" src="https://user-images.githubusercontent.com/101482/166835787-8a89ff17-3d20-46e2-82f3-a3575939ac82.png">

---

## Option B: Using a tooltip 

This option is a little simpler in terms of the effect on the UI, since we wouldn't be affecting the page layout, just adding the tooltip layer above it. Instead of the disclosure icon to expand/collapse the date range lines, we'd use an info icon that is a trigger for a tooltip:

<img width="993" alt="tooltip-none" src="https://user-images.githubusercontent.com/101482/166836095-5b686378-93b3-410a-8783-e4fd76f774b6.png">

---

A user interested in knowing when exactly this stream was previously the default stream can mouseover/keyboard select the info icon to reveal the tooltip with the date range:

<img width="985" alt="tooltip-one" src="https://user-images.githubusercontent.com/101482/166836232-7edbc833-99d2-4def-91f8-6be476acd80e.png">

---

And if the stream was previously the default stream more than once:

<img width="993" alt="tooltip-two" src="https://user-images.githubusercontent.com/101482/166836275-f66c2adf-6c13-4724-925a-a93870b3d150.png">

---

If we decide to go with the tooltip option, a variation we could consider is to start using a "Previous default" badge for streams where that applies. This would make the display in the streams index table a bit more consistent, possibly at the expense of the availability of the date range info being a bit harder to recognize:

<img width="994" alt="Screen Shot 2022-05-04 at 4 46 01 PM" src="https://user-images.githubusercontent.com/101482/166842896-c33f8103-af85-45a7-8366-12b279c7796e.png">

---

It would, however, enable us to easily display the start date of the default stream using a consistent pattern.

Whichever option we decide to implement, we might be able to make the displayed date range info look a bit better than in my mockups with more thoughtful styling; I didn't want to get bogged down by that until we know which option we're going to go with.

**Comment by corylown** [comment]
I'm interested in what others think, but my preference is the tooltip approach using the yellow "Previous default" badge.

**Comment by ggeisler** [comment]
Closing this in favor of #787, since we've decide which option to go with.
