### ISSUE TITLE
Update stream/provider show page with previous stream info

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#771]
This issue is closely related to #769 in that whichever option (expand/collapse hidden date range info or use a tooltip to display it) we decide to go with, we probably should use that option for both that issue and this one.

When the user is viewing the stream show page for a non-default stream, we want the user to know if that stream was ever the default stream, and if so, give the user a way to know the date range(s) it was the default stream. As with #769, I can think of two options that we might consider. 

With either option, there is one change I wanted to make to the stream page anyway that becomes relevant for this issue:

- [ ] Move the "Last updated:" line from below the page header to the top of the stream metadata box
- [ ] Add a divider or bottom border to separate that line from the file/records metadata elements

<img width="1164" alt="either-option" src="https://user-images.githubusercontent.com/101482/166839851-1ef05550-a6a7-4eb2-85aa-f4f59a364070.png">

---

Beyond that, the two options for giving the user access to a non-default stream's previous date range info are:

- Using a disclosure icon to reveal hidden line(s) showing the date range(s) the current stream was previously the default
- Using a tooltip to display the date range(s) the current stream was previously the default

## Option A: Using a disclosure icon
With this option, when a stream has previously been the default stream, we would add the line `Was previously the default stream` with a disclosure icon below the "Last updated" line/divider, with one or more additional lines containing the date range(s) below it, hiding them by default. This lets the user know the stream was previously the default stream:

<img width="1164" alt="disclosure" src="https://user-images.githubusercontent.com/101482/166840348-48201d2a-eddd-4697-beb8-380a016cfa4e.png">

---

If the user is interested in knowing the date range that stream was previously the default stream, they can reveal it using the disclosure icon:

<img width="1164" alt="disclosure-one" src="https://user-images.githubusercontent.com/101482/166840539-3ee8c85e-05ce-4fc9-9ea3-7908d7b6ec7b.png">

---

If there is more than one date range to display, we just show additional date ranges on a new line:

<img width="1164" alt="disclosure-two" src="https://user-images.githubusercontent.com/101482/166840601-dbbe6b8a-f63f-42d3-a2d9-4d37d621a8e3.png">

---

(I don't love the styling of this -- kind of busy with similar text -- but I can work on that if we end up going with this option.)

## Option B: Using a tooltip 
Even more than in #769, the tooltip option is little simpler in terms of the effect on the UI, since we wouldn't be changing the size of the stream metadata box too much, just adding the tooltip layer above it. Instead of the disclosure icon to expand/collapse the date range lines, we'd use an info icon that is a trigger for a tooltip:

<img width="1164" alt="non-default-tooltip-icon" src="https://user-images.githubusercontent.com/101482/166840817-df558304-c3aa-491a-9d73-d6dd5079afc7.png">

---

A user interested in knowing when exactly this stream was previously the default stream can mouseover/keyboard select the info icon to reveal the tooltip with the date range:

<img width="1164" alt="non-default-one" src="https://user-images.githubusercontent.com/101482/166840846-b2492aa1-9fd0-4ef0-846d-81b6adc36f11.png">

---

And if the stream was previously the default stream more than once:

<img width="1164" alt="non-default-two" src="https://user-images.githubusercontent.com/101482/166840873-f16e33a7-09d3-4cfc-a9aa-46f8c00c411e.png">

---

One advantage of the tooltip option on the streams show page is that it would give us a good way of enabling the user to see when the **default stream** became the default stream. We could simply add an info icon to the "Default" badge and use that for the tooltip:

<img width="1164" alt="tooltip-default-showing" src="https://user-images.githubusercontent.com/101482/166841064-e7612ec7-7f13-496a-ba0f-f725359aa888.png">

---

We could also take that one step further, by using a "Previous default" badge for streams where that applies. It's a bit of an awkwardly long badge, but the advantage is we could skip adding anything about the previous default date range(s) to the streams metadata box:

<img width="1165" alt="Screen Shot 2022-05-04 at 4 46 27 PM" src="https://user-images.githubusercontent.com/101482/166843110-749d3983-8d52-4b05-b030-31a843918c19.png">

---

If we don't go with the tooltip option I don't see a good way of providing the equivalent information for the default stream without adding it to the streams metadata box directly, which feels unpleasant to me. We'd be increasing the vertical size and visual clutter of the default stream metadata box for something that I assume for most users isn't information they often need to know.

**Comment by corylown** [comment]
I prefer the badge/tooltip option here as well.

**Comment by JohnMarkOckerbloom** [comment]
Again, assuming the result meets accessibility requirements, I'm good with option B, like in #769.

**Comment by ggeisler** [comment]
Closing this in favor of the more actionable #786, given we've chosen one of the options discussed above.
