### ISSUE TITLE
Update Streams index page table, add tooltip for status badges

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#787]
Related to #786, in that we want to use the same badge/tooltip approach as described in that ticket. Aside that that part, there are a handful of minor table arrangement updates.

## Table updates

<img width="1009" alt="Screen Shot 2022-05-06 at 11 20 02 AM" src="https://user-images.githubusercontent.com/101482/167196271-9ce436f8-f6dc-491e-828c-94d6e385b4c0.png">

- [x] **A:** Move the "Name" column to be the first two column of the table. 
- [x] **B:** Add a `Status` heading for the second column (it doesn't currently have a heading, and is the first column).
- [x] **C:** Add an `Actions` column heading, centered, for the last column that displays the "Make default" and "Destroy" buttons (if the user has permissions to those).
- [x] **C:** Swap order of the the "Make default" and "Destroy" buttons.
- [x] **D:** I'm not sure if this is represented in another ticket, but I believe we want to prevent any stream that was previously a default from being made the default again. So we should not display the "Make default" button for previously default streams.
- [x] **E:** Change the label of the "Destroy" button to "Delete".
- [x] **F:** When a stream was previously the default stream, add a `Previous default` badge to its Status column. Styling is `badge bg-warning text-dark` (I forgot to update the badge label color in my mockup, but it should be dark).
- [x] **F:** Update the current default stream badge with the `text-dark` class so its label is also dark text.
- [x] **F:** For both badges, add an `info-circle-fill` icon to the badge.
- [x] I'm not sure how the current table is sorted, but it probably should be changed to sort by the "Last updated" column, most recent first (my mockup doesn't show it that way, just because I was following the current implementation).

## Add tooltip to badge to display default stream date range

<img width="1009" alt="Screen Shot 2022-05-06 at 11 32 43 AM" src="https://user-images.githubusercontent.com/101482/167197791-55a102bf-6628-4598-9cb3-7ad7833979bd.png">

---

<img width="1009" alt="Screen Shot 2022-05-06 at 11 32 58 AM" src="https://user-images.githubusercontent.com/101482/167197814-7f912835-907d-4819-b909-1697f319e1ae.png">

---

This is the same as described in #786:

- [x] Trigger a Bootstrap tooltip by mouseover/keyboard selection of the info icon in the stream status badge.
- [x] If the stream is a previous default, display the start and end date/time values separated by "`to`.
- [x] If the stream is the current default, use the text `Default since` followed by the date/time it became the default stream.
- [x] A previous default stream might have more than one date range when it was previously the default. If so, display each date range on a separate line.

Note that the requirement to display multiple date ranges means we will likely need to use HTML elements inside the tooltip markup, such as wrapping each date range line in a `<div>` or `<p>`.  Also, to ensure the tooltips work for keyboard and screenreaders, we might have to wrap the badge tooltip in a link. See https://getbootstrap.com/docs/5.0/components/tooltips/#markup for more about this.

**Comment by marlo-longley** [comment]
@ggeisler thanks for all these details, getting close! A couple things:

1. change Destroy to Delete -- last week @corylown  and I went through the app and aligned permissions for delete vs destroy, this button triggers the destroy on the backend, so I'm hesitant to change it again

3. For now we are assuming a stream can be the default more than once, so I'm leaving the button for now

**Comment by ggeisler** [comment]
@marlo-longley 

> change Destroy to Delete -- last week @corylown and I went through the app and aligned permissions for delete vs destroy, this button triggers the destroy on the backend, so I'm hesitant to change it again

Hmm, not sure we are talking about the same thing here. I'm suggesting we change the button label to "Delete" simply because "Destroy" is a default Rails term that is developer jargon; it makes more sense to developers than to end users who have no knowledge about the underlying system (i.e., most web applications enable their users to remove something by "deleting" it, not "destroying" it; end users don't normally think in terms of "destroying" a post or comment or whatever in a web app). I'm not suggesting the action triggered by the button is any different. Selecting the button labeled "Delete" would do the same destroy-the-stream action as it currently does.

I guess I don't know what this means:

> aligned permissions for delete vs destroy

because I don't know how they are different?

> For now we are assuming a stream can be the default more than once, so I'm leaving the button for now

Sure, as long as the UI reflects how we want to handle making streams the default, sounds fine.

**Comment by marlo-longley** [comment]
Thanks @ggeisler 

I guess the word Destroy is already common throughout buttons the app, and it also aligns with developer jargon/backend actions. For example see the /organizations page, where admins can Destroy an organization. I understand you are only talking about the label for the button on this page. I will change the label to Delete if that's your preference.

**Comment by ggeisler** [comment]
I plan to go through the app for consistency on things like button labels at some point, but I wanted to wait until we have more of the intended UI changes complete. So this isn't an intentional one-off label inconsistency, it's just one step in the process of improving the UI from its MVP state.

To be clear, from a UX point of view consistency of button labels with how Rails and developers refer to the corresponding actions is not as important as providing our end users with labels that are clear to them. For example, while there are probably isolated, overlooked exceptions, I don't think we use the term "Destroy" for buttons in any of the SUL applications our team works on.

**Comment by marlo-longley** [comment]
Sounds good thanks for clarifying! @ggeisler
