### ISSUE TITLE
No mailer daemon on the ubuntu servers by default

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#804]
From @cbeer 's note on #670 

> Adding a new issue to the pile. There's no mailer daemon on the ubuntu servers by default:
> 
> ```
> /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/socket.rb:1214:in `__connect_nonblock': Network is unreachable - connect(2) for [::1]:25 (Errno::ENETUNREACH)
> ```

**Comment by cbeer** [comment]
> [kamchan] I just manually started postfix and sent mail.  Need to see why it doesn’t automatically start
