### ISSUE TITLE
Is "Provider" checkbox editable by org owners?

### ISSUE THREAD

**Issue by JohnMarkOckerbloom** [pod4lib/aggregator#807]
I can't tell for sure from here, but it looks from the interface and the chart that org owners can edit anything on the "organization details" tab under "manage organization", including the checkbox indicating whether the organization is a provider or not.

This seems to me like an uncommon and major enough operation that it's probably best not to let org owners toggle this checkbox.   (It seems to me most likely to be toggled by mistake than intentionally.  I don't see orgs newly assuming or dropping their provider status often after joining the system, and if they do, the change could be made by someone with the highest admin privileges.  Changing it without warrant could potentially mess up how we're managing uploads.)

What are others' thoughts on this?

**Comment by corylown** [comment]
I think we should probably restrict this attribute to POD Admin only or even remove it from the UI aside from org account creation.

**Comment by ggeisler** [comment]
Yeah, it seems extremely unlikely for an organization to have a need to change this after the organization is created, so I like the idea of displaying it on the "new" version of the form and hiding it on the "edit" version of the form (version seen after the org has already been created).
