### ISSUE TITLE
Make it easier to find Consumer-only org(s)

### ISSUE THREAD

**Issue by ggeisler** [pod4lib/aggregator#811]
While the provider page reorganization makes the providers table more accurate (it doesn't include consumer-only orgs who don't have the data presented in the table), it does present a problem in that there is currently no obvious place to find consumer-only orgs (we only have one, but maybe there will be more in the future). 

We need a way to get to a list of consumer-only organizations without cluttering the UI with a link for a seldom-needed action (given there is only one consumer-only org).

**Comment by ggeisler** [comment]
Below is a proposed path forward on this issue. We first need to decide on Option A or B (or hear other suggestions), but assuming one of the options sounds okay, the last section of this comment has details for the table needed for either option.

To be clear, we are really designing this feature just for POD admins, because regardless of their level of privileges, any logged-in user of a consumer-only organization can always get to their organization page in two ways:
- On the homepage: when they are logged in they see their Organization section in the middle of the page with several links
- From any page in the application: they can use the user menu in the topbar to access a link to their organization home

Below are two potential options for the POD admin case. I don't love either, but keep in mind that we can revisit a solution in the future if and when there are more consumer-only organizations and other options might make more sense.

## Option A: Add a "Consumers" main menu item and corresponding standalone page
This is the most obvious option, add a "Consumers" main menu item and a corresponding new page to the application:

<img width="1093" alt="Screen Shot 2022-05-20 at 1 54 38 PM" src="https://user-images.githubusercontent.com/101482/169611880-372df7d4-d9ec-44d2-8843-58a27e76d025.png">

---

**Advantages:**
- Clear where to find the Consumer organizations
- Would likely continue to be a good option if and when we add more consumer-only organizations
- Would also potentially work if we decided all logged-in users should be able to see/access consumer-only organizations

**Disadvantages:**
- Adding a menu item to the topbar menu makes scanning and using the existing options more difficult; there are already several other things going on in the topbar menu (POD logo/title, user menu) so the difference between four and five menu items isn't as trivial as it might seem at first. And this is for a likely seldom-used page.



## Option B: Add a POD admin only section to the Providers page
This is admittedly a little kludgy, but since it is only a restricted set of users who would see it, it might be a viable option, as least for the immediate future.

We wouldn't add a menu item to the topbar menu or create a new page as in Option A, but instead would add a section to the **Providers page** that only POD admins see:

<img width="1093" alt="Screen Shot 2022-05-20 at 1 56 24 PM" src="https://user-images.githubusercontent.com/101482/169611622-8cbcb982-f9cd-4583-8d13-a4fb0b27ec82.png">

---

**Advantages:**
- We don't add visual clutter to the topbar as in Option A for a seldom-used page
- Although there's an unfortunate semantic issue (going to the "Providers" page to see the consumer-only organizations) with this solution, this is the page you already go to when you want to see all POD organizations, so the behavior might be easy to learn despite the semantic issue.

**Disadvantages:**
- Going to "Providers" to find a link to a consumer-only organization is not very intuitive and feels a bit awkward. Again, however, once POD-admins know this is where to find the list of consumer-only organizations, this disadvantage is not likely much of an issue.



## Consumer-only organizations table
Whichever option we go with, the consumer-only organizations table is the same:

<img width="1093" alt="Screen Shot 2022-05-20 at 1 57 49 PM" src="https://user-images.githubusercontent.com/101482/169611671-09a824f4-a8ab-40bf-b4ae-280a21b38beb.png">

---

- [ ] **A:** Page/section heading: If we go with Option A, `Consumer-only organizations` is an `<h1>` heading with a `class="h2"` attribute. If we go with Option B, `Consumer-only organizations` is an `<h2>` heading for a new section on the Activity page, between the two existing sections.

The table for this section is generally similar to the providers table, although the middle columns are different.
- [ ] **B:**  Same as in the providers table, but with a heading of `Consumer`. Table column is the logo (if it exits, which it doesn't currently for IndexData, however) and the name of the consumer organization, linked to the home page of the consumer (the Users page `../organizations/indexdata/users`).
- [ ] **C:** Users column that shows how many users the consumer organization has.
- [ ] **D:** The POD contact email address if it exists (it doesn't currently for IndexData, but I think we should include it because it seems like a handy place to show it when it does exist, especially since there isn't much else to show in the table -- and this feels like something we should encourage IndexData to provide?).
- [ ] **E:** Actions column(s). `Edit` should go to the Organization details tab (`../organizations/indexdata/organization_details`). `Delete` doesn't match the label of the corresponding button in the providers table, but we will update that table to match later.

**Comment by corylown** [comment]
I'm leaning toward option B -- adding the table for consumer-only orgs on the provider page. As Gary points out, this would only appear for POD Admins who will learn the location.

**Comment by ggeisler** [comment]
Regarding Option C proposed by @thatbudakguy, I'm not opposed to that if it makes sense to others. I'll just note that:

- As @thatbudakguy says, this makes the consumers table visible to **all** POD users, not just POD admins, which is different from the initial requirement so we'd just want to make sure this is okay
- I think it's been mentioned before that any POD organization might be a consumer, so the "consumer-only" designation does have some meaning. I'm not sure if calling the table "Data consumer organizations" would create confusion or not.
- If we went with this option I'd suggest that the table be the first section of the page

**Comment by corylown** [comment]
I still think option B is the approach I prefer for now.
