### ISSUE TITLE
OAI: add a setDescription element to the ListSets response that indicates whether the stream is the current default

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#814]
It might also be worth adding the date ranges when the stream was the default or the start date if it is currently the default.

Should the organization's slug or name be included in the setDescription?

See notes on "Stream-specific sets" in this story: https://github.com/pod4lib/aggregator/issues/417

**Comment by JohnMarkOckerbloom** [comment]
Yes, it would also be helpful to have the setDescription include a code for the institution that created the stream.  (It would also be good for the stream name to include the organization name, but a specific code in the setDescription may be easier to automatically process.)

I'm not sure whether the slug or the LC MARC code is better to use as the code.  Either can be changed in the UI by an org owner at present as far as I know, but at least the MARC code is supposed to match an externally assigned persistent identifier.  Though if we're already using the slug in other consumption contexts (such as ResourceSync consumption) it might be good to use it here too, and advise org owners not to change the slug without good reason.

**Comment by corylown** [comment]
We use the slug throughout the application, the slug is generally easier to understand at a glance than the MARC org code, and I'm not sure all data providers have added a MARC code, so I think the slug is preferable in this case.
