### ISSUE TITLE
Paging on Activity page always switches tab back to the first tab.

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#826]
Ideally, going to a different page would keep you on the same tab on the Activity page.

**Comment by marlo-longley** [comment]
I don't know another way to keep track of the previous active tab besides using localStorage. If that approach seems OK, I'll go for it. @corylown

**Comment by marlo-longley** [comment]
@corylown do you mean paging through the Uploads table? This is potentially irrelevant now when https://github.com/pod4lib/aggregator/pull/841 merges.

**Comment by corylown** [comment]
@marlo-longley right, I think this is irrelevant with the activity summary only appearing on page one.
