### ISSUE TITLE
Make sure there's a fallback for organization slug value

### ISSUE THREAD

**Issue by marlo-longley** [pod4lib/aggregator#836]
Copied from Slack:
If I don't provide a slug on creation, rails makes my new org viewable at `/organizations/3` rather than `organizations/slug` I'm curious because I was just cruising through creating some dummy orgs, and left the slug blank. While creating the second org without a slug, I got this error. Two orgs can't both have blanks slugs because of `t.index ["slug"], name: "index_organizations_on_slug", unique: true` in the schema. 

![Screen Shot 2022-05-24 at 15 33 21](https://user-images.githubusercontent.com/1328900/170144932-81bf941f-32d0-4dcb-80c4-9d98bba350c4.png)

Possible solutions:
- For the autofill functionality for slug on the create organization form, currently only the placeholder value is being filled. Change it so the value is being filled
- Make slug a required field
- Do something behind the scenes to fill in slug if user does not

**Comment by corylown** [comment]
@marlo-longley I think at the very least we start by implementing solutions 1 & 2:

> 
> * For the autofill functionality for slug on the create organization form, currently only the placeholder value is being filled. Change it so the value is being filled
> * Make slug a required field
