### ISSUE TITLE
What happened to our UTF8 characters? converted to HTML

### ISSUE THREAD

**Issue by cbaksik** [pod4lib/aggregator#910]
Hi - I'm looking at some normalized files from POD and our UTF8 characters are converted to HTML markup:  

`    <datafield ind1="1" ind2="3" tag="245">
      <subfield code="6">880-01</subfield>
      <subfield code="a">al-S&#x323;awa&#x304;&#x2BB;iq al-mursalah &#x2BB;ala&#x301; al-Mulla&#x304; al-Da&#x304;jawi&#x304; wa-atba&#x304;&#x2BB;ihi al-t&#x323;a&#x304;ghiyah /</subfield>
      <subfield code="c">min ta&#x2BC;li&#x304;fa&#x304;t Kha&#x304;n Ba&#x304;dsha&#x304;h ibn Sha&#x304;ndi&#x304;&#x2B9;qal Mas&#x2BB;u&#x304;d ibn Mah&#x323;mu&#x304;d al-Ba&#x304;kista&#x304;ni&#x304;.</subfield>
    </datafield>`

I thought I had checked how these were handled last year but I must have missed it. (Or maybe we talked about this and I'm forgetting?) 

Is there a reason these are converted to html encoding? I'm looking in VuFind, the discovery interface ReShare/IndexData is using and I'm seeing that Unicode is not handled correctly at all: https://borrowdirect.reshare.indexdata.com/Record/f5c79b55-f0e9-4278-a244-aa579e94aef8#details

For example, VuFind displays: Ä°stanbulâun sokak kÃ¶pekleri /

but should be  İstanbul’un sokak köpekleri

Was it expected that consumers convert the data on their end? MARCxml is supposed to be UTF8, which is what we're sending. 

Thanks,
Corinna

**Comment by corylown** [comment]
@cbaksik this should not be causing character display issues in VuFind. Numeric and named character references are valid in XML and should not prevent consumers of the data from correctly interpreting the characters for display. I'm not sure what the path is for reporting issues to IndexData, but I think this is something they'll need to investigate.

**Comment by corylown** [comment]
James is aware of the issue and I assume IndexData will investigate and let me know if they need anything or have questions from POD's side of things.
