### ISSUE TITLE
Wire up pod-worker-a and pod-worker-b to run background jobs for prod

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#931]
They are currently not set up: https://github.com/pod4lib/aggregator/blob/main/config/deploy/prod.rb#L1

**Comment by jcoyne** [comment]
This is blocked until `/opt/app/pod/aggregator/shared/storage` is a volume that is mounted on all 3 nodes.  Otherwise workers are looking for files in places that don't exist in those VMs.

**Comment by corylown** [comment]
Completed during db/redis/ubuntu migration on 1/26/2023
