### ISSUE TITLE
Migrate from pod.stanford.edu to pod-prod.stanford.edu

### ISSUE THREAD

**Issue by jcoyne** [pod4lib/aggregator#938]
pod-prod is the new ubuntu server. 

Currently waiting on a db migration: https://github.com/sul-dlss/operations-tasks/issues/3245#issuecomment-1387398153

**Comment by tallenaz** [comment]
See details on the pending db migration: https://github.com/sul-dlss/operations-tasks/issues/3245#issuecomment-1400749607
