### ISSUE TITLE
Lots of ActiveStorage::FileNotFoundErrors are occurring.

### ISSUE THREAD

**Issue by jcoyne** [pod4lib/aggregator#972]
* https://app.honeybadger.io/projects/77305/faults/92642497
* https://app.honeybadger.io/projects/77305/faults/84932160
* https://app.honeybadger.io/projects/77305/faults/85315260
* https://app.honeybadger.io/projects/77305/faults/92873316

It looks like ~50k errors.

**Comment by corylown** [comment]
I think we might be seeing this: https://github.com/rails/rails/issues/37304

TL;DR
ActiveStorage attachments are stored using an after_commit callback. These callbacks are executed in _reverse order_. In our Upload model we're enqueuing jobs that try to download and use the file before the file is actually attached: https://github.com/pod4lib/aggregator/blob/0824488c5d783498c44c3b61b820c73b7cfae8cc/app/models/upload.rb#L21

I'm going to try moving `has_many_attached` after the `after_save_commit` callbacks that enqueue the jobs to see if this resolves the issue.

**Comment by corylown** [comment]
Seems fixed:
<img width="1133" alt="Screenshot 2023-04-12 at 8 54 35 AM" src="https://user-images.githubusercontent.com/458247/231463758-d3749646-4cd8-430c-bfca-471bce284eb1.png">
